# -*- coding: utf-8 -*-


def definisciAvanzamentiStoria():
    dictAvanzamentoStoria = {}

    # la key del dictionary descrive l'evento appena compiuto
    i = 0
    dictAvanzamentoStoria["inizio"] = i
    i += 1
    dictAvanzamentoStoria["dialogoSognoSara1"] = i
    i += 1
    dictAvanzamentoStoria["tutorialMovimento"] = i
    i += 1
    dictAvanzamentoStoria["aperturaPrimoCofanetto"] = i
    i += 1
    dictAvanzamentoStoria["tutorialUtilizzoOggetti"] = i
    i += 1
    dictAvanzamentoStoria["tutorialBattaglia"] = i
    i += 1
    dictAvanzamentoStoria["tutorialOggettiBattaglia"] = i
    i += 1
    dictAvanzamentoStoria["dialogoSognoSara2"] = i
    i += 1
    dictAvanzamentoStoria["dialogoSognoSara3"] = i
    i += 1
    dictAvanzamentoStoria["primoCambioPersonaggio"] = i
    i += 1
    dictAvanzamentoStoria["dialogoCasaHansSara1"] = i
    i += 1
    dictAvanzamentoStoria["tutorialChiusuraPorte"] = i
    i += 1
    dictAvanzamentoStoria["ottenutoBicchiere"] = i
    i += 1
    dictAvanzamentoStoria["ottenutoBicchiereAcqua"] = i
    i += 1
    dictAvanzamentoStoria["dialogoCasaHansSara2"] = i
    i += 1
    dictAvanzamentoStoria["ingressoForestaCadetta"] = i
    i += 1
    dictAvanzamentoStoria["tutorialCampoVisivo"] = i
    i += 1
    dictAvanzamentoStoria["tutorialDifesa"] = i
    i += 1
    dictAvanzamentoStoria["quartaStanzaForestaCadetta"] = i
    i += 1
    dictAvanzamentoStoria["quintaStanzaForestaCadetta"] = i
    i += 1
    dictAvanzamentoStoria["tutorialRecuperoPvDifesa"] = i
    i += 1
    dictAvanzamentoStoria["incontroFiglioUfficiale"] = i
    i += 1
    dictAvanzamentoStoria["rimessaMusicaDopoDialogoConSam"] = i
    i += 1
    dictAvanzamentoStoria["trovatoLegna1"] = i
    i += 1
    dictAvanzamentoStoria["trovatoLegna2"] = i
    i += 1
    dictAvanzamentoStoria["trovatoLegna3"] = i
    i += 1
    dictAvanzamentoStoria["legnaDepositata"] = i
    i += 1
    dictAvanzamentoStoria["legnaReportataSam"] = i
    i += 1
    dictAvanzamentoStoria["inizioUltimoDialogoHans"] = i
    i += 1
    dictAvanzamentoStoria["fineUltimoDialogoHans"] = i
    i += 1
    dictAvanzamentoStoria["creatoCinghialiForesta5"] = i
    i += 1
    dictAvanzamentoStoria["attaccoCinghiale"] = i
    i += 1
    dictAvanzamentoStoria["secondoCambioPersonaggio"] = i
    i += 1
    dictAvanzamentoStoria["monologoRisveglioSara"] = i
    i += 1
    dictAvanzamentoStoria["trovatoMappaDiario"] = i
    dictAvanzamentoStoria["mappaCasa"] = i
    i += 1
    dictAvanzamentoStoria["tutorialMappaDiario"] = i
    i += 1
    dictAvanzamentoStoria["monologoIndicazioniArmaturaNonno"] = i
    i += 1
    dictAvanzamentoStoria["inizioRicercaChiaveRipostiglio"] = i
    i += 1
    dictAvanzamentoStoria["trovataChiaveRipostiglio"] = i
    i += 1
    dictAvanzamentoStoria["armaturaNonno1"] = i
    i += 1
    dictAvanzamentoStoria["armaturaNonno2"] = i
    i += 1
    dictAvanzamentoStoria["armaturaNonno3"] = i
    i += 1
    dictAvanzamentoStoria["armaturaNonno4"] = i
    i += 1
    dictAvanzamentoStoria["armaturaNonnoCompletata"] = i
    i += 1
    dictAvanzamentoStoria["ingressoForestaCadettaSara"] = i
    dictAvanzamentoStoria["mappaForestaCadetta"] = i
    i += 1
    dictAvanzamentoStoria["accampamentoForestaSara"] = i
    i += 1
    dictAvanzamentoStoria["accampamentoForestaAnalizzato1"] = i
    i += 1
    dictAvanzamentoStoria["accampamentoForestaAnalizzato2"] = i
    i += 1
    dictAvanzamentoStoria["incontratoBrancoLupiNeri"] = i
    i += 1
    dictAvanzamentoStoria["incontratoCinghiale"] = i
    i += 1
    dictAvanzamentoStoria["cinghialeUcciso"] = i
    i += 1
    dictAvanzamentoStoria["cadavereSamDepredato"] = i
    i += 1
    dictAvanzamentoStoria["sotterratoSam"] = i
    i += 1
    dictAvanzamentoStoria["monologoDopoTombaSam"] = i
    i += 1
    dictAvanzamentoStoria["rimessaMusicaDopoTombaSam"] = i
    i += 1
    dictAvanzamentoStoria["ultimaStanzaForesta"] = i
    i += 1
    dictAvanzamentoStoria["uscitoDaForesta"] = i
    i += 1
    dictAvanzamentoStoria["arrivatoAllaPortaDellaCittà"] = i
    i += 1
    dictAvanzamentoStoria["bussatoAllaPortaCittà"] = i
    i += 1
    dictAvanzamentoStoria["dialogoDavidOltreLaPorta"] = i
    i += 1
    dictAvanzamentoStoria["apertoPortaCittà"] = i
    i += 1
    dictAvanzamentoStoria["entratoInCittà"] = i
    dictAvanzamentoStoria["mappaCittà"] = i
    i += 1
    dictAvanzamentoStoria["primoDialogoDavid"] = i
    i += 1
    dictAvanzamentoStoria["arrivoDavidCittà2"] = i
    i += 1
    dictAvanzamentoStoria["arrivoDavidCittà3"] = i
    i += 1
    dictAvanzamentoStoria["arrivoDavidCittà4"] = i
    i += 1
    dictAvanzamentoStoria["arrivoDavidCasaUfficiale"] = i
    i += 1
    dictAvanzamentoStoria["arrivoCasaUfficiale"] = i
    i += 1
    dictAvanzamentoStoria["dialogoArrivoCasaConDavid"] = i
    i += 1
    dictAvanzamentoStoria["arrivoDavidPrimoPiano"] = i
    i += 1
    dictAvanzamentoStoria["giratoDavidVersoIlBasso"] = i
    i += 1
    dictAvanzamentoStoria["presaChiaveStanzaDaLettoDavid"] = i
    i += 1
    dictAvanzamentoStoria["cambiatoPercorsoDavid"] = i
    i += 1
    dictAvanzamentoStoria["inizioBagnoCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["fattoBagnoCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["monologoDopoBagnoDavid"] = i
    i += 1
    dictAvanzamentoStoria["monologoPreCambioPerCenaDavid"] = i
    i += 1
    dictAvanzamentoStoria["cambiataPerCenaDavid"] = i
    i += 1
    dictAvanzamentoStoria["monologoPostCambioPerCenaDavid"] = i
    i += 1
    dictAvanzamentoStoria["sedutoACenaDavid"] = i
    i += 1
    dictAvanzamentoStoria["cenaConDavidIniziata"] = i
    i += 1
    dictAvanzamentoStoria["dialogoCenaDavid1"] = i
    i += 1
    dictAvanzamentoStoria["dialogoCenaDavid2"] = i
    i += 1
    dictAvanzamentoStoria["dialogoCenaDavid3"] = i
    i += 1
    dictAvanzamentoStoria["mammaUfficialeUscitaDallaCena"] = i
    i += 1
    dictAvanzamentoStoria["dialogoCenaDavid4"] = i
    i += 1
    dictAvanzamentoStoria["padreUfficialeUscitoDallaCena"] = i
    i += 1
    dictAvanzamentoStoria["fineDialogoCenaDavid"] = i
    i += 1
    dictAvanzamentoStoria["andatoADormireCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["inizioSognoCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["hansUscitoCamerettaSognoCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["dialogoHansUscitoCamerettaSognoCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["hansAllontanatoCamerettaSognoCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["hansUscitoCasaSognoCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["fineSognoCasaDavid"] = i
    dictAvanzamentoStoria["inizioSecondoGiorno"] = i
    dictAvanzamentoStoria["mercantePozione"] = i
    dictAvanzamentoStoria["mercanteMedicina"] = i
    dictAvanzamentoStoria["mercanteSuperPoz"] = i
    dictAvanzamentoStoria["mercanteBomba"] = i
    dictAvanzamentoStoria["mercanteBomVele"] = i
    dictAvanzamentoStoria["mercanteEsca"] = i
    dictAvanzamentoStoria["mercanteBomAppi"] = i
    dictAvanzamentoStoria["mercanteBomPote"] = i
    i += 1
    dictAvanzamentoStoria["dialogoServoRisveglioSecondoGiorno"] = i
    i += 1
    dictAvanzamentoStoria["alzatoDalLettoSecondoGiorno"] = i
    i += 1
    dictAvanzamentoStoria["monologoDopoAlzatoDalLetto"] = i
    i += 1
    dictAvanzamentoStoria["uscitoCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["chiestoDegliAlloggiAlMercante"] = i
    i += 1
    dictAvanzamentoStoria["trovatoAlloggiProfughi"] = i
    i += 1
    dictAvanzamentoStoria["cercatoHansInAlloggiProfughi"] = i
    i += 1
    dictAvanzamentoStoria["resettatoAvanzamentoDialoghiCittadiniACuiChiediInfo"] = i
    i += 1
    dictAvanzamentoStoria["richiesteMonetePerEntrareInConfraternita"] = i
    i += 1
    dictAvanzamentoStoria["dateMonetePerEntrareInConfraternita"] = i
    i += 1
    dictAvanzamentoStoria["rimosseMonetePerEntrareInConfraternita"] = i
    i += 1
    dictAvanzamentoStoria["rifiutatoDallaBiblioteca"] = i
    i += 1
    dictAvanzamentoStoria["vistoDalServo"] = i
    i += 1
    dictAvanzamentoStoria["dialogoServoCasaDavidDopoSuicidio"] = i
    i += 1
    dictAvanzamentoStoria["servoAndatoPrendereCertificazione"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConGuardiaCasaDavid"] = i
    i += 1
    dictAvanzamentoStoria["servoArrivaConCertificazione"] = i
    i += 1
    dictAvanzamentoStoria["ricevutoCertificatoDalServo"] = i
    i += 1
    dictAvanzamentoStoria["uscitoCasaDavidDopoSuicidio"] = i
    i += 1
    dictAvanzamentoStoria["incontratoIDueAggressori"] = i
    i += 1
    dictAvanzamentoStoria["uccisoPrimoAggressore"] = i
    i += 1
    dictAvanzamentoStoria["dialogoDopoPrimoOmicidio"] = i
    i += 1
    dictAvanzamentoStoria["uccisoSecondoAggressore"] = i
    i += 1
    dictAvanzamentoStoria["monologoDopoUccisioneAggressori"] = i
    i += 1
    dictAvanzamentoStoria["arrivoPrimaGuardia"] = i
    i += 1
    dictAvanzamentoStoria["arrivoSecondaGuardia"] = i
    i += 1
    dictAvanzamentoStoria["fuggitoVersoCittà5"] = i
    i += 1
    dictAvanzamentoStoria["mercanteFuggitoDopoOmicidio"] = i
    i += 1
    dictAvanzamentoStoria["fuggitoVersoCittà7"] = i
    i += 1
    dictAvanzamentoStoria["monologoDopoArrivoInBiblioteca"] = i
    i += 1
    dictAvanzamentoStoria["mostratoCertificatoPerIngressoBiblioteca"] = i
    i += 1
    dictAvanzamentoStoria["incontratoBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["andatoNelloStudioDelBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["dialogoBibliotecarioArrivoNelloStudio"] = i
    i += 1
    dictAvanzamentoStoria["toltoRegistroBibliotecaDallaLibreria"] = i
    i += 1
    dictAvanzamentoStoria["messoRegistroBibliotecaSullaScrivania"] = i
    i += 1
    dictAvanzamentoStoria["dialogoBibliotecarioPreVomito1"] = i
    i += 1
    dictAvanzamentoStoria["dialogoBibliotecarioPreVomito2"] = i
    i += 1
    dictAvanzamentoStoria["vomitatoInBiblioteca"] = i
    i += 1
    dictAvanzamentoStoria["dialogoBibliotecarioPostVomito"] = i
    i += 1
    dictAvanzamentoStoria["sedutaInBiblioteca"] = i
    i += 1
    dictAvanzamentoStoria["ripulitoVomito"] = i
    i += 1
    dictAvanzamentoStoria["bibliotecarioVenutoVersoDiTe"] = i
    i += 1
    dictAvanzamentoStoria["dialogoBibliotecarioDuranteSeduta"] = i
    i += 1
    dictAvanzamentoStoria["alzataDallaSediaInBiblioteca"] = i
    i += 1
    dictAvanzamentoStoria["riavviatoMusicaPostDialogoBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["spiegazioneEnigmaBibliotecario1"] = i
    i += 1
    dictAvanzamentoStoria["eseguitoEsperimentoDiProva1"] = i
    i += 1
    dictAvanzamentoStoria["spiegazioneEnigmaBibliotecario2"] = i
    i += 1
    dictAvanzamentoStoria["eseguitoEsperimentoDiProva2"] = i
    i += 1
    dictAvanzamentoStoria["spiegazioneEnigmaBibliotecario3"] = i
    i += 1
    dictAvanzamentoStoria["scrittiDatiEnigmaBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["spiegazioneEnigmaBibliotecario4"] = i
    i += 1
    dictAvanzamentoStoria["risoltoEnigmaBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["eseguitaVerificaRisultatoEnigma"] = i
    i += 1
    dictAvanzamentoStoria["chiestoDiPensareASceltaPassataNelDialogoBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["pensatoASceltaPassataNelDialogoBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConclusivoEnigmaBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["ripartitaMusicaDopoPensatoASceltaPassataNelDialogoBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["bibliotecarioArrivatoAlRegistro"] = i
    i += 1
    dictAvanzamentoStoria["dialogoBibliotecarioControlloRegistri"] = i
    i += 1
    dictAvanzamentoStoria["andatoACercareImpo"] = i
    i += 1
    dictAvanzamentoStoria["ricercaImpoDiBibliotecario1"] = i
    i += 1
    dictAvanzamentoStoria["ricercaImpoDiBibliotecario2"] = i
    i += 1
    dictAvanzamentoStoria["ricevutoImpo"] = i
    dictAvanzamentoStoria["mercanteAlimantaz"] = i
    dictAvanzamentoStoria["mercanteAlimMiglio"] = i
    i += 1
    dictAvanzamentoStoria["ricevutoImpoPietra"] = i
    i += 1
    dictAvanzamentoStoria["ricaricatoImpoDalBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["introduzioneImpoDalBibliotecario"] = i
    i += 1
    dictAvanzamentoStoria["tutorialImpoPietraMenuSettaImpo"] = i
    dictAvanzamentoStoria["inizioViaggioVersoNeil"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitaBibliotecaDirettoVersoNeil"] = i
    i += 1
    dictAvanzamentoStoria["tutorialMenuPrevisioniImpo"] = i
    i += 1
    dictAvanzamentoStoria["arrivoSelvaArida"] = i
    dictAvanzamentoStoria["mappaSelvaArida"] = i
    i += 1
    dictAvanzamentoStoria["tutorialUsoImpoFrutti"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoSelva2"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoSelva4"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoSelva6"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitaSelva"] = i
    i += 1
    dictAvanzamentoStoria["arrivoAvampostoDiRod"] = i
    i += 1
    dictAvanzamentoStoria["richiesteMonetePerMappaLabirinto"] = i
    dictAvanzamentoStoria["mappaAvampostoDiRod"] = i
    i += 1
    dictAvanzamentoStoria["dateMonetePerMappaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["rimosseMonetePerMappaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["messaMappaLabirintoSulTavolo"] = i
    i += 1
    dictAvanzamentoStoria["riprodottoSuonoMappaLabirintoSulTavolo"] = i
    i += 1
    dictAvanzamentoStoria["arrivatoRodAllAltroTavolo"] = i
    i += 1
    dictAvanzamentoStoria["copiataMappaLabirinto"] = i
    dictAvanzamentoStoria["mappaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["creatoPersonaggioOggettoPerEnigmaMappaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["risoltoEnigmaMappaLabirinto"] = i
    dictAvanzamentoStoria["mappaLabirintoRisolto"] = i
    i += 1
    dictAvanzamentoStoria["eliminatoPersonaggioOggettoPerEnigmaMappaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["monologoPostRisoluzioneEnigma"] = i
    i += 1
    dictAvanzamentoStoria["tutorialStartNelLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["monologoMetaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoEsternoCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoSecondaStanzaEsternoCastello"] = i
    dictAvanzamentoStoria["mappaCastello"] = i
    i += 1
    dictAvanzamentoStoria["convintoServoCastelloAperturaCancello"] = i
    i += 1
    dictAvanzamentoStoria["apertoCancelloPrincipaleCastello"] = i
    i += 1
    dictAvanzamentoStoria["diaolgoServoLanciaDopoAperturaCancello"] = i
    i += 1
    dictAvanzamentoStoria["servoLanciaAndatoInEsternoCastello4"] = i
    i += 1
    dictAvanzamentoStoria["servoLanciaAndatoInEsternoCastello5"] = i
    i += 1
    dictAvanzamentoStoria["saraCamminatoNelCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoEntrataNelCastello"] = i
    i += 1
    dictAvanzamentoStoria["servoLanciaEntratoNelCastello"] = i
    i += 1
    dictAvanzamentoStoria["dialogoServoLanciaEntrataNelCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoInternoCastello12"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoInternoCastello14"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoInternoCastello15"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoInternoCastello18"] = i
    i += 1
    dictAvanzamentoStoria["bloccatoDaGuardiaCastelloInInternoCastello18"] = i
    i += 1
    dictAvanzamentoStoria["giratoVersoImpoPerDarloAlCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoConImpoPrimaDiLasciarloAlleGuardieCastello"] = i
    i += 1
    dictAvanzamentoStoria["guardiaCastelloChiusoPortaLibreriaInternoCastello18"] = i
    dictAvanzamentoStoria["impoPresoDaGuardiaCastello"] = i
    dictAvanzamentoStoria["cenaCastelloServita"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoSalaDaPranzoCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoConSediaSalaDaPranzoCastello"] = i
    i += 1
    dictAvanzamentoStoria["inizioCenaAlCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoCenaAlCastello1"] = i
    i += 1
    dictAvanzamentoStoria["monologoCenaAlCastello2"] = i
    i += 1
    dictAvanzamentoStoria["urloDuranteCenaAlCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoCenaAlCastello3"] = i
    i += 1
    dictAvanzamentoStoria["fineCenaAlCastello"] = i
    i += 1
    dictAvanzamentoStoria["presoChiaveCameraDaLettoCastello"] = i
    i += 1
    dictAvanzamentoStoria["servoLanciaUscitoDaSalaPranzoCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoSecondoPianoCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoAperturaCameraDaLettoCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoAndatoALettoCastello"] = i
    i += 1
    dictAvanzamentoStoria["inizioSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["hansUscitoCamerettaSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["dialogoHansUscitoCamerettaSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["hansAllontanatoCamerettaSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["hansUscitoCasaSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["hansAndatoInCasa4SognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["dialogoHansFuoriCasaSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoForestaSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoLinoMortoSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["apparsiAggressoriForestaSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["dialoghiAggressoriForestaCasaSognoCastello"] = i
    i += 1
    dictAvanzamentoStoria["fineSognoCastello"] = i
    dictAvanzamentoStoria["dormitoNelCastello"] = i
    dictAvanzamentoStoria["servoLanciaTornatoAlCancello"] = i
    i += 1
    dictAvanzamentoStoria["monologoRisveglioNelCastello"] = i
    i += 1
    dictAvanzamentoStoria["alzatoDalLettoNelCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoAlzatoDalLettoNelCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoStanza15CastelloSecondaVolta"] = i
    i += 1
    dictAvanzamentoStoria["monologoAperturaPortaStanza18CastelloSecondaVolta"] = i
    i += 1
    dictAvanzamentoStoria["letto1LibroCastello"] = i
    i += 1
    dictAvanzamentoStoria["letto2LibriCastello"] = i
    i += 1
    dictAvanzamentoStoria["letto3LibriCastello"] = i
    i += 1
    dictAvanzamentoStoria["letto4LibriCastello"] = i
    i += 1
    dictAvanzamentoStoria["letto5LibriCastello"] = i
    i += 1
    dictAvanzamentoStoria["letto6LibriCastello"] = i
    dictAvanzamentoStoria["apertoPortaStanza19CastelloVerso20"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoInternoCastello20"] = i
    i += 1
    dictAvanzamentoStoria["monologoAperturaPortaStudioDiNeil"] = i
    i += 1
    dictAvanzamentoStoria["bussatoPortaStudioDiNeil"] = i
    i += 1
    dictAvanzamentoStoria["primoDialogoNeil"] = i
    i += 1
    dictAvanzamentoStoria["monologoPrimaVistaDiNeil"] = i
    i += 1
    dictAvanzamentoStoria["ricevutoListaStrumentiDaNeil"] = i
    i += 1
    dictAvanzamentoStoria["ripresoImpoDaNeil"] = i
    i += 1
    dictAvanzamentoStoria["inizioViaggioVersoCasaMercante"] = i
    i += 1
    dictAvanzamentoStoria["monologoRipresoImpoDaNeil"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitaStudioDiNeil"] = i
    i += 1
    dictAvanzamentoStoria["monologoNotatoAscensore"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitaCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoNotatoScorciatoiaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["monologoMetaScorciatoiaLabirinto"] = i
    dictAvanzamentoStoria["mappaScorciatoiaLabirinto"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoRetroAvampostoRod"] = i
    i += 1
    dictAvanzamentoStoria["monologoEntratoAvampostoRod"] = i
    i += 1
    dictAvanzamentoStoria["lettoAppuntiInquinamentoAvampostoRod"] = i
    i += 1
    dictAvanzamentoStoria["trovatoChiaveAvampostoDiRod"] = i
    i += 1
    dictAvanzamentoStoria["monologoNotatoAssenzaRodFuoriDallAvamposto"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitaSelvaAridaCercandoRod"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoInCitta9CercandoRod"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoInCitta5CercandoRod"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoPassoMontano"] = i
    dictAvanzamentoStoria["mappaPassoMontano"] = i
    i += 1
    dictAvanzamentoStoria["monologoMetaPassoMontano"] = i
    i += 1
    dictAvanzamentoStoria["rodEntratoNelPalazzo"] = i
    dictAvanzamentoStoria["uscitoDaPassoMontano"] = i
    i += 1
    dictAvanzamentoStoria["monologoVistoRodEntrareNelPalazzo"] = i
    i += 1
    dictAvanzamentoStoria["monologoPreBussataPalazzo"] = i
    i += 1
    dictAvanzamentoStoria["bussatoAlPalazzoDiRodConDialogo"] = i
    i += 1
    dictAvanzamentoStoria["entratoInPalazzoDiRod"] = i
    dictAvanzamentoStoria["mappaPalazzoDiRod"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodDopoEssereEntratoNelPalazzo"] = i
    i += 1
    dictAvanzamentoStoria["rodArrivatoAlTavoloDegliStrumenti"] = i
    i += 1
    dictAvanzamentoStoria["chiesteMonetePerGliStrumenti"] = i
    i += 1
    dictAvanzamentoStoria["presiStrumentiPerStudiareImpo"] = i
    i += 1
    dictAvanzamentoStoria["dateMonetePerStrumentiPerStudiareImpo"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodDopoAverPresoStrumenti"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodAperturaRetroPalazzo"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConclusivoRodAlPalazzo"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitoDalPalazzoDiRod"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoTunnelDiRod"] = i
    dictAvanzamentoStoria["mappaTunnelDiRod"] = i
    i += 1
    dictAvanzamentoStoria["monologoUtilizzoLevaTunnelDiRod"] = i
    i += 1
    dictAvanzamentoStoria["sbloccatoTunnelDiRod"] = i
    i += 1
    dictAvanzamentoStoria["avviatoBattitoCardiacoPreConsegnaStrumenti"] = i
    i += 1
    dictAvanzamentoStoria["dialogoNeilPreConsegnaStrumenti"] = i
    i += 1
    dictAvanzamentoStoria["messoStrumentiSulTavoloDiNeil"] = i
    i += 1
    dictAvanzamentoStoria["riprodottoSuonoStrumentiSulTavoloDiNeil"] = i
    i += 1
    dictAvanzamentoStoria["dialogoNeilPostConsegnaStrumenti"] = i
    i += 1
    dictAvanzamentoStoria["messoImpoSulTavoloDopoConsegnaStrumenti"] = i
    i += 1
    dictAvanzamentoStoria["rimossoImpoMessoSulTavoloDopoConsegnaStrumenti"] = i
    i += 1
    dictAvanzamentoStoria["tentatoDiAndarteneDaNeilConImpoPietra"] = i
    i += 1
    dictAvanzamentoStoria["dialogoNeilSuImpoPietraNonConsegnata"] = i
    i += 1
    dictAvanzamentoStoria["cliccatoImpoPietraPerFuggireDaNeilConImpo"] = i
    i += 1
    dictAvanzamentoStoria["inizioPercorsoPerUscireDalloStudioDiNeilConImpo"] = i
    i += 1
    dictAvanzamentoStoria["uscitoDalloStudioDiNeilConImpo"] = i
    dictAvanzamentoStoria["inizioFugaDalCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitoDalloStudioDiNeilConImpo"] = i
    i += 1
    dictAvanzamentoStoria["chiusoPortaInternoCastello20DaSoldato"] = i
    i += 1
    dictAvanzamentoStoria["dialogoSoldatoInternoCastello20CheChiudePorta"] = i
    i += 1
    dictAvanzamentoStoria["comparsoCadavereSoldatoInternoCastello20"] = i
    i += 1
    dictAvanzamentoStoria["presaChiaveSoldatoInternoCastello20"] = i
    i += 1
    dictAvanzamentoStoria["dialogoAperturaPortaInternoCastello20"] = i
    i += 1
    dictAvanzamentoStoria["apertoPortaInternoCastello20AndandoInInternoCastello19"] = i
    i += 1
    dictAvanzamentoStoria["monologoUscitaInternoCastello20Fuggendo"] = i
    dictAvanzamentoStoria["avviatoMusicaFugaCastello"] = i
    i += 1
    dictAvanzamentoStoria["dialogoNeilFuoriDalCastelloDuranteLaFuga"] = i
    dictAvanzamentoStoria["inizioMusicaAccelerataFugaCastello"] = i
    i += 1
    dictAvanzamentoStoria["arrivatoAlBordoLagoCastelloDuranteLaFuga"] = i
    i += 1
    dictAvanzamentoStoria["dialogoNeilBordoLagoDuranteLaFuga"] = i
    i += 1
    dictAvanzamentoStoria["avvicinatoNeilBordoLagoDuranteLaFuga"] = i
    i += 1
    dictAvanzamentoStoria["buttataNelLagoDuranteLaFuga"] = i
    i += 1
    dictAvanzamentoStoria["fineFugaDalCastello"] = i
    dictAvanzamentoStoria["inizioParteDiRod"] = i
    dictAvanzamentoStoria["stoppatoMusicaFugaCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoRodSuImpoNonVivi"] = i
    i += 1
    dictAvanzamentoStoria["monologoRodCercandoSaraAlPalazzo1"] = i
    i += 1
    dictAvanzamentoStoria["monologoRodCercandoSaraAlPalazzo2"] = i
    i += 1
    dictAvanzamentoStoria["monologoRodDecisoDiParlareConSara"] = i
    i += 1
    dictAvanzamentoStoria["monologoRodArrivoAlCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoRodNotatoSangueNelCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoRodNotatoPianoAscensoreAperto"] = i
    dictAvanzamentoStoria["apertoPortaStanza19CastelloVerso21"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodNeil1"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodNeil2"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodNeil3"] = i
    i += 1
    dictAvanzamentoStoria["uscitoDaInternoCastello21ConRod"] = i
    i += 1
    dictAvanzamentoStoria["monologoRiflessioneRodDopoUscitaDaInternoCastello21"] = i
    i += 1
    dictAvanzamentoStoria["rientratoInInternoCastello21ConRod"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodNeil4"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodNeil5"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodNeil6"] = i
    i += 1
    dictAvanzamentoStoria["dialogoRodNeil7"] = i
    i += 1
    dictAvanzamentoStoria["fineParteDiRod"] = i
    dictAvanzamentoStoria["risveglioSaraResuscitata"] = i
    i += 1
    dictAvanzamentoStoria["alzataDalTavoloLaboratorioCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoPostRimozioneBendeCastello"] = i
    i += 1
    dictAvanzamentoStoria["monologoSpecchioPostRianimazione1"] = i
    i += 1
    dictAvanzamentoStoria["monologoSpecchioPostRianimazione2"] = i
    i += 1
    dictAvanzamentoStoria["girataDavantiAlloSpecchioPostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["monologoSpecchioPostRianimazione3"] = i
    i += 1
    dictAvanzamentoStoria["monologoTentataLuciditaPostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["monologoSpecchioPostRianimazione4"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConSoldatoPostRianimazione1"] = i
    i += 1
    dictAvanzamentoStoria["allontanatoSoldatoPostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConSoldatoPostRianimazione2"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConSoldatoPostRianimazione3"] = i
    i += 1
    dictAvanzamentoStoria["soldatoUscitoDaInternoCastello21PostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["uscitoDaInternoCastello21PostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["soldatoUscitoDaInternoCastello19PostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["riapparsoImpoInternoCastello20PostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["uscitoDaInternoCastello19PostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConBibliotecarioPostRianimazione1"] = i
    i += 1
    dictAvanzamentoStoria["voltatoBibliotecarioDopoIlDialogoPostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["monologoDopoIgnoramentoDiBibliotecarioPostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["sdraiataSulTavoloPostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConNeilPostRianimazione1"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConBibliotecarioPostRianimazione2"] = i
    i += 1
    dictAvanzamentoStoria["dialogoConNeilPostRianimazione2"] = i
    i += 1
    dictAvanzamentoStoria["tempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["alzataDaTavoloPostBloccoTempo"] = i
    i += 1
    dictAvanzamentoStoria["monologoPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["presoImpoPietraPostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["ricaricatoImpoPostRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["monologoConImpoPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoVistoBibliotecarioBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoAccantoABibliotecarioBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoNotatoQtaSoldatiCastelloPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["lettoAppuntiNeilSuRianimazione"] = i
    i += 1
    dictAvanzamentoStoria["creatoOggettoAppuntiRattiNeilInternoCastello21"] = i
    i += 1
    dictAvanzamentoStoria["lettoAppuntiNeilSuRatti"] = i
    i += 1
    dictAvanzamentoStoria["monologoPostLetturaAppuntiNeilSuRatti"] = i
    i += 1
    dictAvanzamentoStoria["monologoPerImpoNonBloccatoPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoScomparsaDiNeilPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoPerplessitàIntenzioniDiNeilERenéPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["uscitoDalCastelloPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoCuriositàStatoCittàPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["esplosioneDelVulcano"] = i
    dictAvanzamentoStoria["mappaVistoVulcano"] = i
    i += 1
    dictAvanzamentoStoria["monologoPostEsplosioneDelVulcano1"] = i
    i += 1
    dictAvanzamentoStoria["monologoPostEsplosioneDelVulcano2"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoAvampostoPostEsplosioneVulcano"] = i
    i += 1
    dictAvanzamentoStoria["monologoNemiciBloccatiSelvaArida"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoCittàPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoSilenzioCittàPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoNemiciBloccatiPassoMontano"] = i
    i += 1
    dictAvanzamentoStoria["monologoFreddoNonPercepitoPassoMontanoPostTempoBloccato"] = i
    i += 1
    dictAvanzamentoStoria["monologoArrivoPalazzo1PostEsplosioneVulcano"] = i

    i += 100
    i += 1
    dictAvanzamentoStoria["sbloccatoCaverna"] = i
    i += 1
    dictAvanzamentoStoria["arrivoIngressoVulcano"] = i
    i += 1
    dictAvanzamentoStoria["liberatoDaiControllori"] = i
    i += 1
    dictAvanzamentoStoria["apertoPortaStanza8Castello"] = i
    i += 1
    dictAvanzamentoStoria["passatiMoltiAnni"] = i

    i += 1
    dictAvanzamentoStoria["mappaCaverna"] = i
    i += 1
    dictAvanzamentoStoria["mappaVulcano"] = i
    i += 1
    dictAvanzamentoStoria["mappaTunnelSubacqueo"] = i
    i += 1
    dictAvanzamentoStoria["mappaLaboratorio"] = i

    return dictAvanzamentoStoria


def definisciStanze():
    dictStanze = {}
    vetStanzePacifiche = []

    # la key del dictionary descrive la stanza
    i = 1
    dictStanze["sognoSara1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["sognoSara2"] = i
    i += 1
    dictStanze["sognoSara3"] = i
    i += 1
    dictStanze["sognoSara4"] = i
    i += 1
    dictStanze["casaHansSara1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["casaHansSara2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["casaHansSara3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["casaHansSara4"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["forestaCadetta1"] = i
    i += 1
    dictStanze["forestaCadetta2"] = i
    i += 1
    dictStanze["forestaCadetta3"] = i
    i += 1
    dictStanze["forestaCadetta4"] = i
    i += 1
    dictStanze["forestaCadetta5"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["forestaCadetta6"] = i
    i += 1
    dictStanze["forestaCadetta7"] = i
    i += 1
    dictStanze["forestaCadetta8"] = i
    i += 1
    dictStanze["forestaCadetta9"] = i
    i += 1
    dictStanze["stradaPerCittà1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["stradaPerCittà2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["stradaPerCittà3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città4"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città5"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città6"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città7"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città8"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città9"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["città10"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["casaDavid1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["casaDavid2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["casaDavid3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["biblioteca1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["biblioteca2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["biblioteca3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["stradaPerSelvaArida1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["stradaPerSelvaArida2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["selvaArida1"] = i
    i += 1
    dictStanze["selvaArida2"] = i
    i += 1
    dictStanze["selvaArida3"] = i
    i += 1
    dictStanze["selvaArida4"] = i
    i += 1
    dictStanze["selvaArida5"] = i
    i += 1
    dictStanze["selvaArida6"] = i
    i += 1
    dictStanze["selvaArida7"] = i
    i += 1
    dictStanze["selvaArida8"] = i
    i += 1
    dictStanze["selvaArida9"] = i
    i += 1
    dictStanze["selvaArida10"] = i
    i += 1
    dictStanze["selvaArida11"] = i
    i += 1
    dictStanze["selvaArida12"] = i
    i += 1
    dictStanze["selvaArida13"] = i
    i += 1
    dictStanze["selvaArida14"] = i
    i += 1
    dictStanze["selvaArida15"] = i
    i += 1
    dictStanze["selvaArida16"] = i
    i += 1
    dictStanze["avampostoDiRod1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["avampostoDiRod2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["avampostoDiRod3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto4"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto5"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto6"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto7"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto8"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto9"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto10"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto11"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto12"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto13"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto14"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto15"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto16"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto17"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto18"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto19"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto20"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto21"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto22"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["labirinto23"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["esternoCastello1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["esternoCastello2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["esternoCastello3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["esternoCastello4"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["esternoCastello5"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello4"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello5"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello6"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello7"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello8"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello9"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello10"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello11"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello12"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello13"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello14"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello15"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello16"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello17"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello18"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello19"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello20"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["internoCastello21"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["scorciatoiaLabirinto1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["scorciatoiaLabirinto2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["stradaPerPassoMontano1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["stradaPerPassoMontano2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["passoMontano1"] = i
    i += 1
    dictStanze["passoMontano2"] = i
    i += 1
    dictStanze["passoMontano3"] = i
    i += 1
    dictStanze["passoMontano4"] = i
    i += 1
    dictStanze["passoMontano5"] = i
    i += 1
    dictStanze["passoMontano6"] = i
    i += 1
    dictStanze["passoMontano7"] = i
    i += 1
    dictStanze["passoMontano8"] = i
    i += 1
    dictStanze["passoMontano9"] = i
    i += 1
    dictStanze["passoMontano10"] = i
    i += 1
    dictStanze["palazzoDiRod1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["palazzoDiRod2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["palazzoDiRod3"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["palazzoDiRod4"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["palazzoDiRod5"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["tunnelDiRod1"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["tunnelDiRod2"] = i
    vetStanzePacifiche.append(i)
    i += 1
    dictStanze["tunnelDiRod3"] = i
    vetStanzePacifiche.append(i)

    i += 100
    i += 1
    dictStanze["caverna1"] = i
    i += 1
    dictStanze["tunnelSubacqueo1"] = i
    vetStanzePacifiche.append(i)

    return dictStanze, vetStanzePacifiche


def definisciPorte(dictStanze):
    vetPorte = []

    stanza = dictStanze["sognoSara4"]
    vetPorte += [stanza, 15, 9, False]

    stanza = dictStanze["casaHansSara1"]
    vetPorte += [stanza, 6, 9, False]
    vetPorte += [stanza, 7, 6, False]
    vetPorte += [stanza, 25, 3, False]
    vetPorte += [stanza, 26, 11, False]

    stanza = dictStanze["forestaCadetta1"]
    vetPorte += [stanza, 6, 7, False]
    vetPorte += [stanza, 19, 12, False]
    stanza = dictStanze["forestaCadetta2"]
    vetPorte += [stanza, 22, 9, False]
    vetPorte += [stanza, 22, 2, False]
    vetPorte += [stanza, 13, 10, False]
    stanza = dictStanze["forestaCadetta3"]
    vetPorte += [stanza, 12, 7, False]
    vetPorte += [stanza, 16, 9, False]
    vetPorte += [stanza, 16, 15, False]
    stanza = dictStanze["forestaCadetta4"]
    vetPorte += [stanza, 18, 2, False]
    vetPorte += [stanza, 15, 10, False]
    vetPorte += [stanza, 18, 14, False]
    vetPorte += [stanza, 21, 14, False]
    stanza = dictStanze["forestaCadetta6"]
    vetPorte += [stanza, 7, 12, False]
    vetPorte += [stanza, 9, 6, False]
    vetPorte += [stanza, 13, 7, False]
    vetPorte += [stanza, 22, 10, False]
    vetPorte += [stanza, 26, 9, False]
    stanza = dictStanze["forestaCadetta7"]
    vetPorte += [stanza, 27, 3, False]
    vetPorte += [stanza, 28, 4, False]
    vetPorte += [stanza, 22, 3, False]
    vetPorte += [stanza, 16, 2, False]
    vetPorte += [stanza, 13, 6, False]
    vetPorte += [stanza, 13, 10, False]
    vetPorte += [stanza, 3, 9, False]
    stanza = dictStanze["forestaCadetta8"]
    vetPorte += [stanza, 25, 9, False]
    vetPorte += [stanza, 29, 10, False]
    vetPorte += [stanza, 24, 15, False]
    vetPorte += [stanza, 16, 9, False]
    vetPorte += [stanza, 7, 10, False]
    vetPorte += [stanza, 5, 9, False]

    stanza = dictStanze["casaDavid3"]
    vetPorte += [stanza, 12, 8, False]
    vetPorte += [stanza, 10, 11, False]

    stanza = dictStanze["selvaArida1"]
    vetPorte += [stanza, 11, 11, False]
    stanza = dictStanze["selvaArida4"]
    vetPorte += [stanza, 9, 9, False]
    stanza = dictStanze["selvaArida5"]
    vetPorte += [stanza, 14, 12, False]
    stanza = dictStanze["selvaArida7"]
    vetPorte += [stanza, 6, 3, False]
    vetPorte += [stanza, 20, 5, False]
    stanza = dictStanze["selvaArida9"]
    vetPorte += [stanza, 10, 5, False]
    stanza = dictStanze["selvaArida12"]
    vetPorte += [stanza, 16, 4, False]
    vetPorte += [stanza, 28, 5, False]
    stanza = dictStanze["selvaArida13"]
    vetPorte += [stanza, 4, 11, False]
    vetPorte += [stanza, 15, 12, False]
    stanza = dictStanze["selvaArida14"]
    vetPorte += [stanza, 14, 4, False]
    vetPorte += [stanza, 15, 4, False]
    vetPorte += [stanza, 16, 4, False]
    stanza = dictStanze["selvaArida15"]
    vetPorte += [stanza, 18, 10, False]
    vetPorte += [stanza, 21, 11, False]
    vetPorte += [stanza, 24, 3, False]
    vetPorte += [stanza, 28, 4, False]
    stanza = dictStanze["selvaArida16"]
    vetPorte += [stanza, 20, 4, False]
    vetPorte += [stanza, 21, 3, False]

    stanza = dictStanze["internoCastello3"]
    vetPorte += [stanza, 14, 6, False]
    vetPorte += [stanza, 22, 10, False]
    vetPorte += [stanza, 25, 6, False]
    stanza = dictStanze["internoCastello4"]
    vetPorte += [stanza, 11, 6, False]
    vetPorte += [stanza, 22, 6, False]
    stanza = dictStanze["internoCastello5"]
    vetPorte += [stanza, 10, 7, False]
    vetPorte += [stanza, 18, 8, False]
    vetPorte += [stanza, 20, 4, False]
    vetPorte += [stanza, 23, 7, False]
    vetPorte += [stanza, 25, 4, False]
    vetPorte += [stanza, 28, 8, False]
    stanza = dictStanze["internoCastello8"]
    vetPorte += [stanza, 7, 7, False]
    stanza = dictStanze["internoCastello10"]
    vetPorte += [stanza, 8, 5, False]
    vetPorte += [stanza, 12, 9, False]
    stanza = dictStanze["internoCastello11"]
    vetPorte += [stanza, 12, 5, False]
    vetPorte += [stanza, 19, 5, False]
    stanza = dictStanze["internoCastello15"]
    vetPorte += [stanza, 5, 8, False]
    vetPorte += [stanza, 14, 4, False]
    stanza = dictStanze["internoCastello16"]
    vetPorte += [stanza, 3, 6, False]
    vetPorte += [stanza, 8, 6, False]
    vetPorte += [stanza, 12, 3, False]
    vetPorte += [stanza, 12, 9, False]
    vetPorte += [stanza, 15, 11, False]
    vetPorte += [stanza, 16, 5, False]
    stanza = dictStanze["internoCastello17"]
    vetPorte += [stanza, 6, 6, False]
    vetPorte += [stanza, 8, 3, False]
    vetPorte += [stanza, 8, 13, False]
    vetPorte += [stanza, 11, 7, False]
    stanza = dictStanze["internoCastello18"]
    vetPorte += [stanza, 17, 12, False]
    stanza = dictStanze["internoCastello20"]
    vetPorte += [stanza, 10, 6, False]
    vetPorte += [stanza, 17, 9, False]

    stanza = dictStanze["palazzoDiRod2"]
    vetPorte += [stanza, 12, 8, False]
    vetPorte += [stanza, 17, 10, False]
    vetPorte += [stanza, 22, 13, False]

    return vetPorte


def definisciCofanetti(dictStanze):
    vetCofanetti = []

    stanza = dictStanze["sognoSara1"]
    vetCofanetti += [stanza, 13, 10, False]
    stanza = dictStanze["sognoSara2"]
    vetCofanetti += [stanza, 13, 5, False]
    vetCofanetti += [stanza, 28, 7, False]
    stanza = dictStanze["sognoSara3"]
    vetCofanetti += [stanza, 3, 13, False]

    stanza = dictStanze["casaHansSara1"]
    vetCofanetti += [stanza, 23, 13, False]
    vetCofanetti += [stanza, 24, 15, False]
    vetCofanetti += [stanza, 27, 15, False]
    vetCofanetti += [stanza, 29, 14, False]
    stanza = dictStanze["casaHansSara3"]
    vetCofanetti += [stanza, 21, 10, False]

    stanza = dictStanze["forestaCadetta1"]
    vetCofanetti += [stanza, 8, 2, False]
    vetCofanetti += [stanza, 4, 15, False]
    vetCofanetti += [stanza, 27, 2, False]
    stanza = dictStanze["forestaCadetta2"]
    vetCofanetti += [stanza, 18, 14, False]
    vetCofanetti += [stanza, 11, 2, False]
    vetCofanetti += [stanza, 5, 9, False]
    stanza = dictStanze["forestaCadetta3"]
    vetCofanetti += [stanza, 20, 2, False]
    vetCofanetti += [stanza, 5, 13, False]
    vetCofanetti += [stanza, 21, 9, False]
    stanza = dictStanze["forestaCadetta4"]
    vetCofanetti += [stanza, 29, 9, False]
    vetCofanetti += [stanza, 10, 2, False]
    stanza = dictStanze["forestaCadetta6"]
    vetCofanetti += [stanza, 12, 2, False]
    vetCofanetti += [stanza, 21, 2, False]
    stanza = dictStanze["forestaCadetta7"]
    vetCofanetti += [stanza, 26, 15, False]
    vetCofanetti += [stanza, 2, 4, False]
    stanza = dictStanze["forestaCadetta8"]
    vetCofanetti += [stanza, 2, 6, False]
    stanza = dictStanze["forestaCadetta9"]
    vetCofanetti += [stanza, 5, 11, False]

    stanza = dictStanze["città4"]
    vetCofanetti += [stanza, 17, 5, False]
    stanza = dictStanze["città8"]
    vetCofanetti += [stanza, 27, 8, False]
    stanza = dictStanze["città10"]
    vetCofanetti += [stanza, 4, 3, False]

    stanza = dictStanze["selvaArida1"]
    vetCofanetti += [stanza, 6, 5, False]
    vetCofanetti += [stanza, 6, 12, False]
    vetCofanetti += [stanza, 12, 11, False]
    stanza = dictStanze["selvaArida2"]
    vetCofanetti += [stanza, 16, 3, False]
    stanza = dictStanze["selvaArida3"]
    vetCofanetti += [stanza, 16, 14, False]
    vetCofanetti += [stanza, 17, 12, False]
    stanza = dictStanze["selvaArida4"]
    vetCofanetti += [stanza, 12, 11, False]
    vetCofanetti += [stanza, 18, 11, False]
    stanza = dictStanze["selvaArida5"]
    vetCofanetti += [stanza, 13, 10, False]
    stanza = dictStanze["selvaArida6"]
    vetCofanetti += [stanza, 4, 10, False]
    vetCofanetti += [stanza, 11, 2, False]
    stanza = dictStanze["selvaArida7"]
    vetCofanetti += [stanza, 4, 2, False]
    vetCofanetti += [stanza, 13, 9, False]
    vetCofanetti += [stanza, 24, 7, False]
    stanza = dictStanze["selvaArida8"]
    vetCofanetti += [stanza, 14, 15, False]
    stanza = dictStanze["selvaArida9"]
    vetCofanetti += [stanza, 7, 15, False]
    vetCofanetti += [stanza, 13, 12, False]
    stanza = dictStanze["selvaArida10"]
    vetCofanetti += [stanza, 7, 3, False]
    vetCofanetti += [stanza, 9, 2, False]
    stanza = dictStanze["selvaArida11"]
    vetCofanetti += [stanza, 3, 13, False]
    vetCofanetti += [stanza, 7, 14, False]
    vetCofanetti += [stanza, 25, 7, False]
    stanza = dictStanze["selvaArida12"]
    vetCofanetti += [stanza, 15, 2, False]
    vetCofanetti += [stanza, 28, 9, False]
    stanza = dictStanze["selvaArida13"]
    vetCofanetti += [stanza, 2, 14, False]
    vetCofanetti += [stanza, 6, 5, False]
    vetCofanetti += [stanza, 10, 10, False]
    stanza = dictStanze["selvaArida14"]
    vetCofanetti += [stanza, 6, 11, False]
    vetCofanetti += [stanza, 10, 13, False]
    vetCofanetti += [stanza, 22, 11, False]
    stanza = dictStanze["selvaArida15"]
    vetCofanetti += [stanza, 20, 5, False]
    stanza = dictStanze["selvaArida16"]
    vetCofanetti += [stanza, 20, 7, False]

    stanza = dictStanze["labirinto2"]
    vetCofanetti += [stanza, 10, 6, False]
    stanza = dictStanze["labirinto4"]
    vetCofanetti += [stanza, 24, 11, False]
    stanza = dictStanze["labirinto5"]
    vetCofanetti += [stanza, 18, 10, False]
    stanza = dictStanze["labirinto9"]
    vetCofanetti += [stanza, 18, 8, False]
    stanza = dictStanze["labirinto11"]
    vetCofanetti += [stanza, 24, 9, False]
    stanza = dictStanze["labirinto14"]
    vetCofanetti += [stanza, 7, 8, False]
    stanza = dictStanze["labirinto17"]
    vetCofanetti += [stanza, 16, 10, False]
    stanza = dictStanze["labirinto23"]
    vetCofanetti += [stanza, 16, 10, False]

    stanza = dictStanze["internoCastello1"]
    vetCofanetti += [stanza, 2, 12, False]
    stanza = dictStanze["internoCastello2"]
    vetCofanetti += [stanza, 29, 5, False]
    stanza = dictStanze["internoCastello3"]
    vetCofanetti += [stanza, 27, 8, False]
    stanza = dictStanze["internoCastello4"]
    vetCofanetti += [stanza, 13, 12, False]
    stanza = dictStanze["internoCastello5"]
    vetCofanetti += [stanza, 8, 6, False]
    vetCofanetti += [stanza, 18, 3, False]
    vetCofanetti += [stanza, 25, 9, False]
    stanza = dictStanze["internoCastello6"]
    vetCofanetti += [stanza, 25, 7, False]
    stanza = dictStanze["internoCastello7"]
    vetCofanetti += [stanza, 23, 2, False]
    stanza = dictStanze["internoCastello9"]
    vetCofanetti += [stanza, 23, 2, False]
    stanza = dictStanze["internoCastello10"]
    vetCofanetti += [stanza, 16, 7, False]
    vetCofanetti += [stanza, 26, 13, False]
    stanza = dictStanze["internoCastello11"]
    vetCofanetti += [stanza, 10, 12, False]
    vetCofanetti += [stanza, 15, 7, False]
    vetCofanetti += [stanza, 16, 7, False]
    vetCofanetti += [stanza, 21, 12, False]
    stanza = dictStanze["internoCastello12"]
    vetCofanetti += [stanza, 3, 2, False]
    stanza = dictStanze["internoCastello13"]
    vetCofanetti += [stanza, 15, 3, False]
    stanza = dictStanze["internoCastello15"]
    vetCofanetti += [stanza, 3, 3, False]
    stanza = dictStanze["internoCastello16"]
    vetCofanetti += [stanza, 4, 15, False]
    vetCofanetti += [stanza, 14, 7, False]
    stanza = dictStanze["internoCastello17"]
    vetCofanetti += [stanza, 14, 8, False]
    stanza = dictStanze["internoCastello18"]
    vetCofanetti += [stanza, 29, 14, False]
    stanza = dictStanze["internoCastello20"]
    vetCofanetti += [stanza, 19, 8, False]
    vetCofanetti += [stanza, 25, 8, False]
    stanza = dictStanze["internoCastello21"]
    vetCofanetti += [stanza, 6, 12, False]
    vetCofanetti += [stanza, 14, 9, False]
    vetCofanetti += [stanza, 25, 8, False]

    stanza = dictStanze["avampostoDiRod3"]
    vetCofanetti += [stanza, 24, 12, False]

    stanza = dictStanze["passoMontano1"]
    vetCofanetti += [stanza, 11, 14, False]
    vetCofanetti += [stanza, 16, 9, False]
    vetCofanetti += [stanza, 21, 8, False]
    stanza = dictStanze["passoMontano2"]
    vetCofanetti += [stanza, 3, 3, False]
    vetCofanetti += [stanza, 4, 12, False]
    vetCofanetti += [stanza, 6, 4, False]
    vetCofanetti += [stanza, 29, 5, False]
    stanza = dictStanze["passoMontano3"]
    vetCofanetti += [stanza, 4, 15, False]
    vetCofanetti += [stanza, 7, 2, False]
    stanza = dictStanze["passoMontano4"]
    vetCofanetti += [stanza, 11, 2, False]
    stanza = dictStanze["passoMontano5"]
    vetCofanetti += [stanza, 3, 2, False]
    vetCofanetti += [stanza, 6, 15, False]
    vetCofanetti += [stanza, 26, 11, False]
    vetCofanetti += [stanza, 28, 13, False]
    stanza = dictStanze["passoMontano6"]
    vetCofanetti += [stanza, 18, 2, False]
    stanza = dictStanze["passoMontano7"]
    vetCofanetti += [stanza, 12, 15, False]
    stanza = dictStanze["passoMontano8"]
    vetCofanetti += [stanza, 4, 7, False]
    stanza = dictStanze["passoMontano9"]
    vetCofanetti += [stanza, 7, 14, False]
    vetCofanetti += [stanza, 26, 14, False]
    stanza = dictStanze["passoMontano10"]
    vetCofanetti += [stanza, 7, 2, False]

    stanza = dictStanze["palazzoDiRod2"]
    vetCofanetti += [stanza, 26, 10, False]

    stanza = dictStanze["tunnelDiRod2"]
    vetCofanetti += [stanza, 17, 8, False]

    return vetCofanetti
