# -*- coding: utf-8 -*-


LIV__ATT_AUM = {"ita": u"<*>#bold#LV +:<*> Attacco aumentato"}
LIV__DIF_AUM = {"ita": u"<*>#bold#LV +:<*> Difesa aumentata"}
LIV__PUN_VIT_AUM = {"ita": u"<*>#bold#LV +:<*> Punti vita aumentati"}
HAI_TRO_NIE = {"ita": u"Hai trovato: Niente"}
HAI_TRO_AZI = {"ita": u"Hai trovato: Azio-Impofoglia"}
HAI_TRO_POZ = {"ita": u"Hai trovato: Pozione"}
HAI_GI_TRO_POZ = {"ita": u"Hai già troppe Pozioni!"}
HAI_TRO_IMP_PIC = {"ita": u"Hai trovato: Impofrutto piccolo"}
HAI_GI_TRO_IMP_PIC = {"ita": u"Hai già troppi impofrutti piccoli!"}
HAI_TRO_MED = {"ita": u"Hai trovato: Medicina"}
HAI_GI_TRO_MED = {"ita": u"Hai già troppe Medicine!"}
HAI_TRO_SUP = {"ita": u"Hai trovato: Super pozione"}
HAI_GI_TRO_SUP = {"ita": u"Hai già troppe Superpozioni!"}
HAI_TRO_IMP_GRA = {"ita": u"Hai trovato: Impofrutto grande"}
HAI_GI_TRO_IMP_GRA = {"ita": u"Hai già troppi impofrutti grandi!"}
HAI_TRO_BOM = {"ita": u"Hai trovato: Bomba"}
HAI_GI_TRO_BOM = {"ita": u"Hai già troppe Bombe!"}
HAI_TRO_BOM_VEL = {"ita": u"Hai trovato: Bomba velenosa"}
HAI_GI_TRO_BOM_VEL = {"ita": u"Hai già troppe Bombe velenose!"}
HAI_TRO_ESC = {"ita": u"Hai trovato: Esca"}
HAI_GI_TRO_ESC = {"ita": u"Hai già troppe Esche!"}
HAI_TRO_BOM_APP = {"ita": u"Hai trovato: Bomba appiccicosa"}
HAI_GI_TRO_BOM_APP = {"ita": u"Hai già troppe Bombe appiccicose!"}
HAI_TRO_BOM_POT = {"ita": u"Hai trovato: Bomba potenziata"}
HAI_GI_TRO_BOM_POT = {"ita": u"Hai già troppe Bombe potenziate!"}
HAI_TRO_SPA_DI_FER = {"ita": u"Hai trovato: Spada di ferro"}
HAI_TRO_SPA_DAC = {"ita": u"Hai trovato: Spadone d'acciaio"}
HAI_TRO_SPA_DI_NEI = {"ita": u"Hai trovato: Spada di Neil"}
HAI_TRO_SPA_DI_ROD = {"ita": u"Hai trovato: Spada di Rod"}
HAI_TRO_ARC_DI_LEG = {"ita": u"Hai trovato: Arco di legno"}
HAI_TRO_ARC_DI_FER = {"ita": u"Hai trovato: Arco di ferro"}
HAI_TRO_ARC_DI_NEI = {"ita": u"Hai trovato: Arco di Neil"}
HAI_TRO_ARC_DI_ROD = {"ita": u"Hai trovato: Arco di Rod"}
HAI_TRO_ARM_DI_PEL = {"ita": u"Hai trovato: Armatura di pelle"}
HAI_TRO_ARM_DAC = {"ita": u"Hai trovato: Armatura d'acciaio"}
HAI_TRO_ARM_DI_NEI = {"ita": u"Hai trovato: Armatura di Neil"}
HAI_TRO_ARM_DI_ROD = {"ita": u"Hai trovato: Armatura di Rod"}
HAI_TRO_SCU_DI_PEL = {"ita": u"Hai trovato: Scudo di pelle"}
HAI_TRO_SCU_DAC = {"ita": u"Hai trovato: Scudo d'acciaio"}
HAI_TRO_SCU_DI_NEI = {"ita": u"Hai trovato: Scudo di Neil"}
HAI_TRO_SCU_DI_ROD = {"ita": u"Hai trovato: Scudo di Rod"}
HAI_TRO_GUA_VIT = {"ita": u"Hai trovato: Guanti vitali"}
HAI_TRO_GUA_DIF = {"ita": u"Hai trovato: Guanti difensivi"}
HAI_TRO_GUA_OFF = {"ita": u"Hai trovato: Guanti offensivi"}
HAI_TRO_GUA_CON = {"ita": u"Hai trovato: Guanti confortevoli"}
HAI_TRO_COL_RIG = {"ita": u"Hai trovato: Collana rigenerante"}
HAI_TRO_COL_MED = {"ita": u"Hai trovato: Collana medicinale"}
HAI_TRO_POR = {"ita": u"Hai trovato: Portafortuna"}
HAI_TRO_ASS = {"ita": u"Hai trovato: Assorbilampo"}
HAI_TRO_SAC_ENE_PIC = {"ita": u"Hai trovato: Sacca Energetica piccola"}
HAI_TRO_SAC_ENE_DIS = {"ita": u"Hai trovato: Sacca Energetica discreta"}
HAI_TRO_SAC_ENE_CAP = {"ita": u"Hai trovato: Sacca Energetica capiente"}
HAI_TRO_SAC_ENE_GRA = {"ita": u"Hai trovato: Sacca Energetica grande"}
HAI_TRO_SAC_ENE_ENO = {"ita": u"Hai trovato: Sacca Energetica enorme"}
HAI_TRO_CON = {"ita": u"Hai trovato: Condizio-Impofoglia"}
HAI_TRO_CEL_DI_MEM = {"ita": u"Hai trovato: Cella di memoria"}
HAI_TRO_50_MON = {"ita": u"Hai trovato: 50 monete"}
HAI_TRO_1_FRE = {"ita": u"Hai trovato: 1 freccia"}
HAI_GI_TRO_FRE = {"ita": u"Hai già troppe frecce!"}
MON_TRO_ = {"ita": u"Monete trovate: "}
PRE_PRO_AZI = {"ita": u"Previsione prossima azione"}
MOV_VER_IMP = {"ita": u"Movimento verso impopietra"}
IST_ESE_SAL_INT_DI_SAR = {"ita": u"Istruzione eseguita salvo interferenza di Sara"}
SAR_CON_PV__80 = {"ita": u"Sara con <*>#italic#PV<*> < 80%"}
SAR_CON_PV__50 = {"ita": u"Sara con <*>#italic#PV<*> < 50%"}
SAR_CON_PV__30 = {"ita": u"Sara con <*>#italic#PV<*> < 30%"}
SAR_CON_VEL = {"ita": u"Sara con veleno"}
IMPO_SURRISCALDATO = {"ita": u"Impo surriscaldato"}
IMP_CON_PE__80 = {"ita": u"Impo con <*>#italic#PE<*> < 80%"}
IMP_CON_PE__50 = {"ita": u"Impo con <*>#italic#PE<*> < 50%"}
IMP_CON_PE__30 = {"ita": u"Impo con <*>#italic#PE<*> < 30%"}
SEM_A_SAR = {"ita": u"Sempre a Sara"}
SEM_A_IMP = {"ita": u"Sempre a Impo"}
NEM_A_CAS = {"ita": u"Nemico a caso"}
NEMICO_VICINO = {"ita": u"Nemico vicino"}
NEMICO_LONTANO = {"ita": u"Nemico lontano"}
NEM_CON_PV__80 = {"ita": u"Nemico con <*>#italic#PV<*> < 80%"}
NEM_CON_PV__50 = {"ita": u"Nemico con <*>#italic#PV<*> < 50%"}
NEM_CON_PV__30 = {"ita": u"Nemico con <*>#italic#PV<*> < 30%"}
NEM_CON_MEN_PV = {"ita": u"Nemico con meno <*>#italic#PV<*>"}
NUM_DI_NEM__1 = {"ita": u"Numero di nemici > 1"}
NUM_DI_NEM__2 = {"ita": u"Numero di nemici > 2"}
NUM_DI_NEM__3 = {"ita": u"Numero di nemici > 3"}
SCOSSA = {"ita": u"Scossa"}
CURA = {"ita": u"Cura"}
ANTIDOTO = {"ita": u"Antidoto"}
FRECCIA_ELETTRICA = {"ita": u"Freccia elettrica"}
TEMPESTA_ELETTRICA = {"ita": u"Tempesta elettrica"}
RAFFREDDAMENTO = {"ita": u"Raffreddamento"}
AUTORICARICA = {"ita": u"Auto-ricarica"}
CURA_P = {"ita": u"Cura +"}
SCOSSA_P = {"ita": u"Scossa +"}
FRE_ELE_P = {"ita": u"Freccia elettrica +"}
VELOCIZZA = {"ita": u"Velocizza"}
CARICA_ATTACCO = {"ita": u"Carica attacco"}
CARICA_DIFESA = {"ita": u"Carica difesa"}
EFFICIENZA = {"ita": u"Efficienza"}
TEM_ELE_P = {"ita": u"Tempesta elettrica +"}
CURA_PP = {"ita": u"Cura ++"}
AUTORICARICA_P = {"ita": u"Auto-ricarica +"}
SCOSSA_PP = {"ita": u"Scossa ++"}
FRE_ELE_PP = {"ita": u"Freccia Elettrica ++"}
TEM_ELE_PP = {"ita": u"Tempesta elettrica ++"}
MOV_VER_OBI_SAL_IN_MEM = {"ita": u"Movimento verso obiettivo salvato in memoria"}
NES_AZI_DA_ESE = {"ita": u"Nessuna azione da eseguire"}
SEI_MORTO = {"ita": u"Sei morto"}
HAI_OTT_ = {"ita": u"Hai ottenuto: "}
A_NOI_UOM_NAS__TOC_UN_TRI_PRI_QUE_DI_SEN_VIV_CON_LA_BEL_ILL_DI_PRE_COM_UNA_REA_FUO_DI_NOI_QUE_NOS_INT_SEN = {"ita": u"<*>#italic#A noi uomini, nascendo, è toccato un triste privilegio: quello di sentirci vivere, con la bella illusione di prendere come una realtà fuori di noi questo nostro interno sentimento...<*>"}
_LUI_PIR = {"ita": u"- Luigi Pirandello"}
ACQUISTA_OGGETTI = {"ita": u"Acquista oggetti"}
OGGETTI_ACQUISTABILI = {"ita": u"Oggetti acquistabili"}
COSTO = {"ita": u"Costo"}
POSSEDUTI = {"ita": u"Posseduti"}
FRECCIA = {"ita": u"Freccia"}
POZIONE = {"ita": u"Pozione"}
IMPOFRUTTO_PICCOLO = {"ita": u"Impofrutto piccolo"}
MEDICINA = {"ita": u"Medicina"}
SUPER_POZIONE = {"ita": u"Super pozione"}
IMPOFRUTTO_GRANDE = {"ita": u"Impofrutto grande"}
BOMBA = {"ita": u"Bomba"}
BOMBA_VELENOSA = {"ita": u"Bomba velenosa"}
ESCA = {"ita": u"Esca"}
BOMBA_APPICCICOSA = {"ita": u"Bomba appiccicosa"}
BOMBA_POTENZIATA = {"ita": u"Bomba potenziata"}
FARETRA = {"ita": u"Faretra"}
TAS_DES_TOR_IND = {"ita": u"Tasto destro: indietro"}
B_TOR_IND = {"ita": u"B: indietro"}
Q_TOR_IND = {"ita": u"Q: indietro"}
NON_HAI_ABB_MON = {"ita": u"Non hai abbastanza monete!"}
MONETE_INSUFFICIENTI = {"ita": u"Monete insufficienti!"}
NON_HO_ABB_MON_DOV = {"ita": u"Non ho abbastanza monete... dovrei?"}
NON_PUO_PRE_ALT = {"ita": u"Non puoi prenderne altre..."}
SPAZIO_INSUFFICIENTE = {"ita": u"Spazio insufficiente!"}
NON_POS_TRA_ALT = {"ita": u"Non posso trasportarne altre..."}
QUA_TE_NE_SER = {"ita": u"Quante te ne servono?"}
QUANTI = {"ita": u"Quanti?"}
QUA_ME_NE_SER = {"ita": u"Quante me ne servono?"}
MON_NEC_I = {"ita": u"(Monete necessarie: %i)"}
CONFERMA = {"ita": u"Conferma"}
ANNULLA = {"ita": u"Annulla"}
PRE_QUE_CHE_TI_SER = {"ita": u"Prendi quello che ti serve."}
COS_MI_SER = {"ita": u"Cosa mi serve?"}
MONETE_ = {"ita": u"Monete: "}
FRECCIA_ = {"ita": u"Freccia:"}
USA_PER_ATT_I_NEM_A_DIS = {"ita": u"Usate per attaccare i nemici a distanza."}
POZIONE_ = {"ita": u"Pozione:"}
REC_100_PV_DI_SAR = {"ita": u"Recupera 100 <*>#italic#PV<*> di Sara."}
SCONOSCIUTO = {"ita": u"Sconosciuto"}
IMPOFRUTTO_PICCOLO_ = {"ita": u"Impofrutto piccolo:"}
REC_250_PE_DI_IMP = {"ita": u"Recupera 250 <*>#italic#PE<*> di Impo."}
MEDICINA_ = {"ita": u"Medicina:"}
CUR_AVV_A_SAR = {"ita": u"Cura avvelenamento a Sara."}
SUPER_POZIONE_ = {"ita": u"Super pozione:"}
REC_300_PV_DI_SAR = {"ita": u"Recupera 300 <*>#italic#PV<*> di Sara."}
IMPOFRUTTO_GRANDE_ = {"ita": u"Impofrutto grande:"}
REC_600_PE_DI_IMP = {"ita": u"Recupera 600 <*>#italic#PE<*> di Impo."}
BOMBA_ = {"ita": u"Bomba:"}
INF_UN_PO_DI_DAN_AI_NEM_SU_CUI_VIE_LAN = {"ita": u"Infligge un po' di danni ai nemici su cui viene lanciata."}
BOMBA_VELENOSA_ = {"ita": u"Bomba velenosa:"}
INF_AVV_AL_NEM_SU_CUI_VIE_LAN = {"ita": u"Infligge avvelenamento al nemico su cui viene lanciata."}
ESCA_ = {"ita": u"Esca:"}
DIS_I_NEM_FIN_NON_VIE_DIS__POS_RIP_PAS_SOP = {"ita": u"Distrae i nemici finché non viene distrutta. È possibile riprenderla passandoci sopra."}
BOMBA_APPICCICOSA_ = {"ita": u"Bomba appiccicosa:"}
DIM_LA_VEL_DEL_NEM_SU_CUI_VIE_LAN = {"ita": u"Dimezza la velocità del nemico su cui viene lanciata."}
BOMBA_POTENZIATA_ = {"ita": u"Bomba potenziata:"}
INF_MOL_DAN_AI_NEM_SU_CUI_VIE_LAN = {"ita": u"Infligge molti danni ai nemici su cui viene lanciata."}
FARETRA_ = {"ita": u"Faretra:"}
PER_DI_TRA_PI_FRE = {"ita": u"Permette di trasportare più frecce."}
TAS_CEN_CAN_TUT = {"ita": u"Tasto centrale: cancella tutto"}
LB = {"ita": u"LB:"}
RB = {"ita": u"RB:"}
Y_CAN_TUT = {"ita": u"Y: cancella tutto"}
SHI_CAN_TUT = {"ita": u"SHIFT: cancella tutto"}
TOR_AL_MEN_PRI = {"ita": u"Tornare al menu principale?"}
USC_DAL_GIO = {"ita": u"Uscire dal gioco?"}
INI_UNA_NUO_PAR = {"ita": u"Iniziare una nuova partita?"}
SI = {"ita": u"Sì"}
NO = {"ita": u"No"}
OFF = {"ita": u"Off"}
TO = {"ita": u"To"}
SLEEP = {"ita": u"Sleep"}
INIZIA = {"ita": u"Inizia"}
CONTINUA = {"ita": u"Continua"}
IMPOSTAZIONI = {"ita": u"Impostazioni"}
ESCI = {"ita": u"Esci"}
TAS_CEN_COM = {"ita": u"Tasto centrale: comandi"}
MENU_COMANDI = {"ita": u"Menu: comandi"}
ESC_COMANDI = {"ita": u"Esc: comandi"}
COMANDI_MOUSE = {"ita": u"Comandi mouse"}
SU_CAS_LIB__MOV = {"ita": u"Su casella libera - Movimento"}
SU_CAS_INT__INT = {"ita": u"Su casella interagibile - Interagisci"}
SU_IMP__ATT__DIS_IMP = {"ita": u"Su impopietra - Attiva / Disatt. impopietra"}
SU_STA_PER__MEN = {"ita": u"Su stato personaggio - Menu"}
SU_ICO_LE__MOD_INT = {"ita": u"Su icona \"Interazione\" - Mod. interazione"}
SU_ICO_SA__SAL_TUR = {"ita": u"Su icona \"SaltaTurno\" - Salta turno"}
MODALIT_INTERAZIONE = {"ita": u"Modalità interazione"}
SU_ICO_LE__RIM_SEL = {"ita": u"Su icona \"Interazione\" - Rimuovi selez."}
MENU = {"ita": u"Menu"}
SU_CAS_NEM__INQ__ATT = {"ita": u"Su casella nemica - Inquadra / Attacca"}
SU_ICO_LE__MOD_MOV = {"ita": u"Su icona \"Interazione\" - Mod. movimento"}
MODALIT_MOVIMENTO = {"ita": u"Modalità movimento"}
SELEZIONA = {"ita": u"Seleziona"}
IND__ESC = {"ita": u"Indietro / Esci"}
CAM_OPE_SE_CON = {"ita": u"Cambia operazione (se consentito)"}
ESC_SE_CON = {"ita": u"Esci (se consentito)"}
COMANDI_CONTROLLER = {"ita": u"Comandi controller"}
CAM_BER_INQ = {"ita": u"Cambia bersaglio inquadrato"}
DESELEZIONA_BERSAGLIO = {"ita": u"Deseleziona bersaglio"}
MOVIMENTO = {"ita": u"Movimento"}
ATT__DIS_IMP = {"ita": u"Attiva / Disattiva impopietra"}
SALTA_TURNO = {"ita": u"Salta turno"}
INTERAGISCI = {"ita": u"Interagisci"}
PUN_SUL_PRO_BER = {"ita": u"Punta sul prossimo bersaglio"}
INQ_BER_PUN = {"ita": u"Inquadra bersaglio puntato"}
SPOSTA_PUNTATORE = {"ita": u"Sposta puntatore"}
ATT__INT = {"ita": u"Attacca / Interagisci"}
COMANDI_TASTIERA = {"ita": u"Comandi tastiera"}
MOD_MOVIMENTO = {"ita": u"Mod. movimento"}
MOD_INTERAZIONE = {"ita": u"Mod. interazione"}
TAS_DES__CEN_TOR_IND = {"ita": u"Tasto destro / centrale: indietro"}
MEN__B_TOR_IND = {"ita": u"Menu / B: indietro"}
ESC__Q_TOR_IND = {"ita": u"Esc / Q: indietro"}
OGGETTI = {"ita": u"Oggetti"}
EQUIPAGGIAMENTO = {"ita": u"Equipaggiamento"}
SETTA_IMPO = {"ita": u"Setta Impo"}
MAPPA = {"ita": u"Mappa"}
DIARIO = {"ita": u"Diario"}
SALVA = {"ita": u"Salva"}
MENU_PRINCIPALE = {"ita": u"Menu principale"}
LV___STR______ESP___STR____ = {"ita": u"LV: %i    Esp: %i / %i"}
LV___STR______ESP___ = {"ita": u"LV: %i    Esp: -- / --"}
PV____STR____ = {"ita": u"PV: %i / %i"}
STATUS_ALTERATI = {"ita": u"Status alterati:"}
PE____STR____ = {"ita": u"PE: %i / %i"}
FRE___STR____ = {"ita": u"Frecce: %i / %i"}
IMP__IRR = {"ita": u"Impo è irraggiungibile!"}
ARMI = {"ita": u"Armi"}
PROTEZIONI = {"ita": u"Protezioni"}
ACCESSORI = {"ita": u"Accessori"}
STATISTICHE = {"ita": u"Statistiche:"}
PUN_VIT_ = {"ita": u"Punti vita: "}
ATT_RAV_ = {"ita": u"Attacco ravvicinato: "}
ATT_A_DIS_ = {"ita": u"Attacco a distanza: "}
DIFESA_ = {"ita": u"Difesa: "}
PRO_PAR_I__PAR_ = {"ita": u"Probabilità parata: "}
NIENTE = {"ita": u"Niente:"}
RIMUOVI_SPADA = {"ita": u"Rimuovi spada."}
SPA_DI_FER = {"ita": u"Spada di ferro:"}
SEM_SPA_DI_FER = {"ita": u"Semplice spada di ferro."}
SPADONE_DACCIAIO = {"ita": u"Spadone d'acciaio:"}
GRA_SPA_DAC_CON_ORN_IN_ORO_STU_PER_PER_ATT_RAP_E_POT = {"ita": u"Grande spadone d'acciaio con ornamenti in oro. Studiato per permettere attacchi rapidi e potenti."}
SPA_DI_NEI = {"ita": u"Spada di Neil:"}
SPA_MOL_LEG_E_AFF_SEM_ESS_STA_RIC_DA_UN_DEN_DI_UNA_BES_ENO = {"ita": u"Spada molto leggera e affilata. Sembra essere stata ricavata da un dente di una bestia enorme."}
SPA_DI_ROD = {"ita": u"Spada di Rod:"}
POT_SPA_COM_DA_MAT_LEG_MA_MOL_RES = {"ita": u"Potentissima spada composta da materiali leggeri ma molto resistenti."}
RIMUOVI_ARCO = {"ita": u"Rimuovi arco."}
ARC_DI_LEG = {"ita": u"Arco di legno:"}
SEM_ARC_IN_LEG_USA_DAL_MAG_PAR_DEI_FOR = {"ita": u"Semplice arco in legno usato dalla maggior parte dei forestieri."}
ARC_DI_FER = {"ita": u"Arco di ferro:"}
ELA_ARC_IN_FER_USA_SOL_DAI_PI_ESP = {"ita": u"Elaborato arco in ferro usato solo dai più esperti."}
ARC_DI_NEI = {"ita": u"Arco di Neil:"}
SOF_ARC_IN_LEG_E_ACC_MOL_LEG_E_POT = {"ita": u"Sofisticato arco in legno e acciaio. Molto leggero e potente."}
ARC_DI_ROD = {"ita": u"Arco di Rod:"}
POT_ARC_COM_DA_MAT_LEG_MA_MOL_RES = {"ita": u"Potentissimo arco composto da materiali leggeri ma molto resistenti."}
RIMUOVI_ARMATURA = {"ita": u"Rimuovi armatura."}
ARM_DI_PEL = {"ita": u"Armatura di pelle:"}
SEM_ARM_IN_PEL = {"ita": u"Semplice armatura in pelle."}
ARMATURA_DACCIAIO = {"ita": u"Armatura d'acciaio:"}
ARM_DAC_CON_ORN_IN_ORO_USA_SOL_DAG_UFF_DEL = {"ita": u"Armatura d'acciaio con ornamenti in oro. Usata solo dagli ufficiali dell'esercito."}
ARM_DI_NEI = {"ita": u"Armatura di Neil:"}
ARM_FOR_DA_MAT_LEG_E_RES_SEM_ESS_STA_RIC_DAL_OSS_DI_UNA_BES = {"ita": u"Armatura formata da materiali leggeri e resistenti. Sembra essere stata ricavata dalle ossa di una bestia."}
ARM_DI_ROD = {"ita": u"Armatura di Rod:"}
ARM_INC_RES_E_LEG = {"ita": u"Armatura incredibilmente resistente e leggera."}
RIMUOVI_SCUDO = {"ita": u"Rimuovi scudo."}
SCU_DI_PEL = {"ita": u"Scudo di pelle:"}
SEM_SCU_IN_PEL = {"ita": u"Semplice scudo in pelle."}
SCUDO_DACCIAIO = {"ita": u"Scudo d'acciaio:"}
SOF_SCU_IN_ACC_E_ORO_STU_PER_RES_GLI_ATT_PI_PES = {"ita": u"Sofisticato scudo in acciaio e oro. Studiato per respingere gli attacchi più pesanti."}
SCU_DI_NEI = {"ita": u"Scudo di Neil:"}
SCU_MOL_LEG_E_RES_SEM_ESS_STA_RIC_DAL_OSS_PI_RES_DI_UNA_QUA_BES = {"ita": u"Scudo molto leggero e resistente. Sembra essere stato ricavato dalle ossa più resistenti di una qualche bestia."}
SCU_DI_ROD = {"ita": u"Scudo di Rod:"}
SCU_INC_RES_E_LEG = {"ita": u"Scudo incredibilmente resistente e leggero."}
RIMUOVI_GUANTI = {"ita": u"Rimuovi guanti."}
GUANTI_VITALI = {"ita": u"Guanti vitali:"}
GUA_CHE_AUM_I_PV_MAS_DEL_POR = {"ita": u"Guanti che aumentano i <*>#italic#PV<*> massimi del portatore."}
GUANTI_DIFENSIVI = {"ita": u"Guanti difensivi:"}
GUA_CHE_CON_DI_SUB_MEN_DAN_GRA_A_UNA_PRE_SAL_DEL_SCU = {"ita": u"Guanti che consentono di subire meno danni grazie a una presa salda dello scudo."}
GUANTI_OFFENSIVI = {"ita": u"Guanti offensivi:"}
GUA_CHE_AUM_LAT_DEL_POR_GRA_A_UNA_PRE_SAL_DEL = {"ita": u"Guanti che aumentano l'attacco del portatore grazie a una presa salda dell'arma."}
GUANTI_CONFORTEVOLI = {"ita": u"Guanti confortevoli:"}
GUA_CHE_AUM_LA_PRO_DI_PAR_GLI_ATT_GRA_A_UNA_PRE_AGE_DEL_SCU = {"ita": u"Guanti che aumentano la probabilità di parare gli attacchi grazie a una presa agevole dello scudo."}
RIMUOVI_COLLANA = {"ita": u"Rimuovi collana."}
COLLANA_RIGENERANTE = {"ita": u"Collana rigenerante:"}
COL_COM_DA_ERB_IL_CUI_ODO_RIP_PV_OGN_TUR = {"ita": u"Collana composta da erbe il cui odore ripristina gradualmente i <*>#italic#PV<*> del portatore."}
COLLANA_MEDICINALE = {"ita": u"Collana medicinale:"}
COL_COM_DA_ERB_IL_CUI_ODO_NEU_LA_TOS_DEL_VEL_NON_HA_EFF_SE_SI__GI_AVV = {"ita": u"Collana composta da erbe il cui odore neutralizza la tossicità del veleno (non ha effetto se si è già avvelenati)."}
PORTAFORTUNA = {"ita": u"Portafortuna:"}
COL_CHE_PER_DI_OTT_PI_MON_DAI_NEM = {"ita": u"Collana che permette di ottenere più monete dai nemici."}
ASSORBILAMPO = {"ita": u"Assorbilampo:"}
COL_CHE_TI_REN_IMM_AGL_ATT_DI_IMP = {"ita": u"Collana che ti rende immune agli attacchi di Impo."}
NOME_OGGETTO = {"ita": u"Nome oggetto"}
QUANTIT = {"ita": u"Quantità"}
INUTILIZZABILE = {"ita": u"Inutilizzabile..."}
USARE = {"ita": u"Usare?"}
REC_100_PV = {"ita": u"Recupera 100 <*>#italic#PV.<*>"}
NUT_PER_UNA_SPE_IN_VIA_DI_EST = {"ita": u"Nutrimento per una specie in via di estinzione..."}
CURA_AVVELENAMENTO = {"ita": u"Cura avvelenamento."}
REC_300_PV = {"ita": u"Recupera 300 <*>#italic#PV.<*>"}
STA_ALT_ = {"ita": u"Status alterati: "}
CONFIGURA_CONTROLLER = {"ita": u"Configura controller"}
SEL_IL_CON_DA_CON = {"ita": u"Seleziona il controller da configurare:"}
INIZIA_CONFIGURAZIONE = {"ita": u"Inizia configurazione"}
CANCELLA_CONFIGURAZIONE = {"ita": u"Cancella configurazione"}
TESTA_CONFIGURAZIONE = {"ita": u"Testa configurazione"}
INDIETRO = {"ita": u"Indietro"}
OPZ_DIS_SOL_ACC_DA_MEN_PRI = {"ita": u"Opzione disponibile solo accedendo da menu principale"}
ATT_QUA_SEC = {"ita": u"Attendi qualche secondo"}
AGG_LIS_CON_COL = {"ita": u"Aggiorna lista controller collegati"}
CLI_I_TAS_ILL = {"ita": u"Clicca i tasti illuminati"}
CON_CHE_I_TAS_PRE_COR_A_QUE_ILL = {"ita": u"Controlla che i tasti premuti corrispondano a quelli illuminati"}
CONTROLLER_CONFIGURATO = {"ita": u"Controller configurato"}
CON_NON_CON = {"ita": u"Controller non configurato"}
NES_CON_RIL = {"ita": u"Nessun controller rilevato"}
CON_TEM_CON = {"ita": u"Controller temporaneamente configurato"}
CON_TEM_NON_CON = {"ita": u"Controller temporaneamente non configurato"}
CON_TEM_MOD = {"ita": u"Configurazione temporaneamente modificata"}
CONFIGURA_TASTIERA = {"ita": u"Configura tastiera"}
SE_LA_TUA_TAS_NON_RIS_LO_STA_QWE_CON_LE_LET_DA_USA_AL_POS_DI_Q_W_E_A_S_E_D_BR_BR_ATT_NEI_TUT_CI_SI_RIF_SEM_ALL_STA_QWE_QUA_VER_SPI_I_COM_DI_GIO = {"ita": u"Se la tua tastiera non rispetta lo standard QWERTY, configura le lettere da usare al posto di Q, W, E, A, S e D. <br> <br> ATTENZIONE: nei tutorial ci si riferirà sempre allo standard QWERTY quando verranno spiegati i comandi di gioco."}
ESC = {"ita": u"Esc"}
SEL_IL_TAS_DA_CON = {"ita": u"Seleziona il tasto da configurare:"}
RESETTA_CONFIGURAZIONE = {"ita": u"Resetta configurazione"}
ESC_TOR_IND = {"ita": u"Esc: indietro"}
IMP_IL_TAS_IND = {"ita": u"Imposta il tasto indicato"}
CAM_RIS_IN_COR = {"ita": u"Cambio risoluzione in corso..."}
LINGUA = {"ita": u"Lingua"}
VOLUME_AUDIO = {"ita": u"Volume audio"}
TASTIERA = {"ita": u"Tastiera"}
CONTROLLER = {"ita": u"Controller"}
RISOLUZIONE = {"ita": u"Risoluzione"}
MODALIT_FINESTRA = {"ita": u"Modalità finestra"}
CON_RIS_OTT = {"ita": u"Controllo risoluzione ottimale"}
ITALIANO = {"ita": u"Italiano"}
ENGLISH = {"ita": u"English"}
CONFIGURA = {"ita": u"Configura"}
RIS_SCO_BR_RAM_RIC___STR__100__GB_SIS___STR__100__GB = {"ita": u"Risoluzione sconsigliata! <br> RAM richiesta: %1.1fGB (sistema: %1.1fGB)"}
RIS_SUP_BR_RAM_RIC___STR__100__GB_SIS___STR__100__GB = {"ita": u"Risoluzione supportata! <br> RAM richiesta: %1.1fGB (sistema: %1.1fGB)"}
SCHERMO_INTERO = {"ita": u"Schermo intero"}
FINESTRA = {"ita": u"Finestra"}
FIN_SEN_BOR = {"ita": u"Finestra senza bordi"}
ATTIVATO = {"ita": u"Attivato"}
DISATTIVATO = {"ita": u"Disattivato"}
DIS_SE_VUO_UTI_BR_UNA_RIS_SCO = {"ita": u"Disattiva se vuoi utilizzare <br> una risoluzione sconsigliata"}
CASA = {"ita": u"Casa"}
_LAB_IN_CUI_HO_VIS_CON_LA_MIA_FAM_FIN__STA_COS_DA_UN_MIO_VEC_ANT_E_DA_ALL__SEM_STA_ABI_DAL_VAR_GEN_DEL_MIA_FAM_SEC_MIO_PAD_HAN_SAR_IL_PRO_PRO_E_LID_NON_LO_ENT_AFF_DUR_DIV_DIS_HAN_HA_DET_DI_NON_VOL_FAR_QUE_LAV_PER_TUT_LA_VIT_DIC_CHE__MON_FAT_E_ANC_INS_A_CAU_DEL_ENO_IMP_E_DEL_SPI_CON = {"ita": u"È l'abitazione in cui ho vissuto con la mia famiglia fin'ora. È stata costruita da un mio vecchio antenato e, da allora, è sempre stata abitata dalle varie generazioni della mia famiglia. Secondo mio padre, Hans sarà il prossimo proprietario e l'idea non lo entusiasma affatto: durante diverse discussioni Hans ha detto di non voler fare questo lavoro per tutta la vita. Dice che è monotono, faticoso e anche instabile a causa delle enormi imposte e della spietata concorrenza."}
CITT = {"ita": u"Città"}
DA_QUA_NE_HO_SEN_PAR_PER_LA_PRI_VOL_HO_SEM_AVU_IL_DES_DI_VIV_DA_QUE_CHE_SO_L_A_TUT__CON_SCE_QUA_MAN_SVO_NEL_VIT_QUE__DIV_POS_GRA_AI_NUO_STR_DI_PRO_CHE_HAN_PER_LA_REA_DI_UN_SIS_IN_CUI_POC_PER_RIE_A_PRO_ABB_ANC_PER_TUT_LE_ALT_LA_PAR_DI_POP_IM_PU_QUI_DED_AD_ALT_ATT_COM_MUS_TEA_STU_SPO_E_CHI_COS = {"ita": u"Da quando ne ho sentito parlare per la prima volta, ho sempre avuto il desiderio di viverci. Da quello che so, lì a tutti è concesso scegliere quale mansione svolgere nella vita. Questo è diventato possibile grazie ai nuovi strumenti di produzione, che hanno permesso la realizzazione di un sistema in cui poche persone riescono a produrre abbastanza anche per tutte le altre. La parte di popolazione \"improduttiva\" può quindi dedicarsi ad altre attività come musica, teatro, studio, sport e chissà cos'altro..."}
AVA_DI_ROD = {"ita": u"Avamposto di Rod"}
UNA_PIC_BAR_CHE_ROD_ESA_IN_MAN_ESA_DEF_AV_QUE_NON__LA_SUA_ABI_MA_A_SUO_DIR_UN_LUO_FON_PER_IL_MAN_DEL_CIT_NON_ROD_NON_MI_ABB_MAI_ISP_MOL_FID_I_SUO_RAG_NON_MI_SON_MAI_SEM_QUE_DI_UN_FOL_ESA_FOR_STA_SEM_SCH = {"ita": u"Una piccola baracca che Rod esalta in maniera esagerata definendola \"avamposto\". Quella non è la sua abitazione, ma, a suo dire, un luogo fondamentale per il mantenimento dell'ecosistema cittadino. Nonostante Rod non mi abbia mai ispirato molta fiducia, i suoi ragionamenti non mi sono mai sembrati quelli di un folle esaltato... forse stava semplicemente scherzando..."}
CASTELLO = {"ita": u"Castello"}
LA_PI_GRA_STR_CHE_ABB_MAI_VIS_FIN_AD_ORA__UN_CAS_COM_DA_ALM_UN_CEN_DI_STA_ABI_DA_NEI_E_DAI_SUO_NUM_SER_IL_VAS_TER_SU_CUI__STA_COS_COM_ANC_LIN_LAB_CHE_DEV_STA_APP_ELA_PER_TEN_LON_I_VIS_IND_IL_SIL_E_IL_COM_DEI_SER_CRE_UNA_CUP_E_SUR = {"ita": u"La più grande struttura che abbia mai visto fino ad ora. È un castello composto da almeno un centinaio di stanze, abitato da Neil e dai suoi numerosi servitori. Il vasto terreno su cui è stato costruito comprende anche l'intero labirinto, che dev'essere stato appositamente elaborato per tenere lontani i visitatori indesiderati. Il silenzio e il comportamento dei servi creano un'atmosfera cupa e surreale..."}
PAL_DI_ROD = {"ita": u"Palazzo di Rod"}
IL_PAL_IN_CUI_DIM_ROD_DEN__TUT_MOL_DIS_CI_SON_FOG_E_CAR_OVU_CON_DEI_SUO_STU_O_PRO_SEM_PI_UNA_SPE_DI_MAG_DOV_TIE_UN_SAC_DI_ROB_VIS_LA_POL_SUG_SCA_NON_CRE_CHE_UTI_EFF_TUT_QUE_OGG_MI_DOM_PER_NON_LI_BUT_BR_LAM_RIC_VAG_IL_CAS_DI_NEI_MA_UN_PO_PI_PIC_E_CON_IL_PAS_MON_AL_POS_DEL_LAB_PER_SCO_LAV_DI_VIA_IND = {"ita": u"Il palazzo in cui dimora Rod. Dentro è tutto molto disordinato, ci sono fogli e cartacce ovunque con dei suoi studi o progetti. Sembra più una specie di magazzino dove tiene un sacco di roba. Vista la polvere sugli scatoloni, non credo che utilizzi effettivamente tutti quegli oggetti. Mi domando perché non li butti... <br> L'ambiente ricorda vagamente il castello di Neil, ma un po' più piccolo e con il Passo Montano al posto del labirinto per scoraggiare l'avvicinamento di viaggiatori indesiderati."}
VULCANO = {"ita": u"Vulcano"}
UNA_MON_CON_UN_CRA_SUL_CIM_SI_TRO_A_OVE_DEL_CIT_OLT_IL_PAS_MON_LHO_VIS_ESP_MEN_USC_DAL_CAS_DI_NEI_ALL_OLT_A_UNE_DIS_DI_ACQ_INC_E_UNA_STR_ROC_CON_DEI_DIS_DI_IMP_C_UN_CAD_CHE_GIA_IN_UNA_CEL_DI_VET = {"ita": u"Una montagna con un cratere sulla cima. Si trova a ovest della città oltre il Passo Montano. L'ho vista esplodere mentre uscivo dal castello di Neil. All'interno, oltre a un'enorme distesa di acqua incandescente e una strana roccia con dei disegni di impo, c'è un cadavere che giace in una cella di vetro."}
LAB_DI_NEI = {"ita": u"Laboratorio di Neil"}
IL_LAB_SEG_DI_NEI_SI_TRO_SUL_FON_DEL_LAG_NON__MOL_GRA_DEN_C_QUA_TAV_CON_DEG_APP_UN_CAL_DI_EVE_E_UNA_CEL_SIM_A_QUE_PRE_NEL_VUL_PER_EV_DA_QUE_DIM_DEN_LA_CEL_C_IL_COR_DI_NEI = {"ita": u"Il laboratorio segreto di Neil. Si trova sul fondale del lago. Non è molto grande, dentro c'è qualche tavolo con degli appunti, un calcolatore di eventi e una cella simile a quella presente nel vulcano per \"evadere da questa dimensione\". Dentro la cella c'è il corpo di Neil."}
FORESTA_CADETTA = {"ita": u"Foresta Cadetta"}
LA_FOR_CHE_MI_HA_SEM_SEP_DAL_CIT_NON_HO_MAI_AVU_IL_PER_DI_ATT_PER_I_MIE_GEN_LA_RIT_TRO_PER_PER_ME_IL_NOM_DER_DAL_FAT_CHE_VIE_UTI_COM_TER_DI_PRO_PER_SEL_TRA_I_GIO_APP_ALL_NOB_I_FUT_UFF_DEL = {"ita": u"La foresta che mi ha sempre separata dalla città... non ho mai avuto il permesso di attraversarla perché i miei genitori la ritenevano troppo pericolosa per me. Il nome deriva dal fatto che viene utilizzata come terreno di prova per selezionare, tra i giovani appartenenti alla nobiltà, i futuri ufficiali dell'esercito."}
SELVA_ARIDA = {"ita": u"Selva Arida"}
DEN_IN_QUE_MOD_PER_UN_TEM_FIT_E_INT_ED_ORA_COM_SOL_DA_SEC_ABU_E_FUN_LE_RAG_DI_QUE_SUO_DEC_NON_SON_NOT_AGL_ABI_LOC_MA_SI_D_PRA_PER_SCO_CHE_CI_SIA_STA_UN_INT_UMA_DIE_PER_QUA_AVR_INT_NEL_FAR_UNA_COS_DEL_GEN = {"ita": u"Denominata in questo modo perché un tempo fitta e intricata ed ora composta soltanto da secchi arbusti e funghi. Le ragioni di questo suo decadimento non sono note agli abitanti locali, ma si dà praticamente per scontato che ci sia stato un intervento umano dietro... perché qualcuno avrebbe interesse nel fare una cosa del genere?"}
LABIRINTO = {"ita": u"Labirinto"}
UN_ENO_TER_EST_COM_DA_SUP_A_CAU_DEL_INN_STR_PER_PRI_DI_PUN_DI_RIF_ROD_MI_HA_FOR_UNA_MAP_CHE_MOS_NEL_DET_LA_SUA_STR_SCO_DI_PRO__MOL_PRO_NON_RIU_A_USC_SE_NON_SI_HA_UN_BUO_SEN_DEL = {"ita": u"Un enorme terreno estremamente complicato da superare a causa delle innumerevoli strade percorribili prive di punti di riferimento. Rod mi ha fornito una mappa che mostra nel dettaglio la sua struttura sconsigliandomi di procedere: è molto probabile non riuscire a uscirne se non si ha un buon senso dell'orientamento."}
PASSO_MONTANO = {"ita": u"Passo Montano"}
UN_PAS_TRA_LE_ALT_A_OVE_DEL_CIT_IN_POC_MET_PIE_IN_QUE_TER_E_QUE_CHE_LO_FAN_NE_PAR_COM_SE_FOS_IL_POS_PI_PER_AL_MON_IN_CIT_NES_SA_MOL_DI_QUE_PAS_ALC_MI_HAN_DET_DI_AVE_VIS_DIV_VOL_ROD_ARR_DA_QUE_PAR = {"ita": u"Un passaggio tra le alture a ovest della città. In pochi mettono piede in quei territori, e quelli che lo fanno ne parlano come se fosse il posto più pericoloso al mondo. In città nessuno sa molto di quei passaggi. Alcuni mi hanno detto di aver visto diverse volte Rod arrivare da quelle parti..."}
TUN_DI_ROD = {"ita": u"Tunnel di Rod"}
_UN_PAS_SIC_E_VEL_TRA_IL_PAL_DI_ROD_E_IL_SUO_AVA_AL_SUO_INT_PAS_UN_TUB_MOL_CHE_PAR_DAL_PAL_E_VA_DA_QUA_PAR_NEL_SEL_ARI_DEV_DI_ROD_MA_MI_DOM_A_CHE_COS_SER = {"ita": u"È un passaggio sicuro e veloce tra il palazzo di Rod e il suo avamposto. Al suo interno passa un tubo molliccio che parte dal palazzo e va da qualche parte nella Selva Arida. Dev'essere di Rod, ma mi domando a che cosa serva..."}
CAVERNA_IMPO = {"ita": u"Caverna Impo"}
UNA_CAV_IN_MEZ_ALL_MON_OCC_ALL_VIV_DEG_ANI_SIM_A_IMP_MA_AGG_DA_QUE_CHE_HO_CAP_ROD_ERA_SOL_AVV_IN_QUE_CUN_PER_REC_IMP_PRO__PER_QUE_CHE_HA_DEC_DI_COS_IL_SUO_PAL_L_ACC_PER_ASS_CHE_NES_ALT_VI_ACC_E_TEN_PER_S_TUT_IL_BOT = {"ita": u"Una caverna in mezzo alle montagne occidentali. All'interno vivono degli animali simili a Impo ma aggressivi. Da quello che ho capito, Rod era solito avventurarsi in questi cunicoli per recuperare impofrutti. Probabilmente è per questo che ha deciso di costruire il suo palazzo lì accanto... per assicurarsi che nessun altro vi accedesse e tenere per sé tutto il bottino..."}
TUNNEL_SUBACQUEO = {"ita": u"Tunnel Subacqueo"}
UN_PAS_SEG_NEI_SOT_DEL_CAS_DI_NEI_CHE_POR_AL_SUO_LAB_PRI_SUL_FON_DEL_LAG_NON_LE_PAR_DEL_TUN_SIA_FAT_DI_UN_MAT_TRA_SIM_AL_VET_NON_SI_RIE_A_OSS_CHI_IL_FON_DEL_BAC_A_CAU_DEL_SOS_CON_CUI__STA_CON = {"ita": u"Un passaggio segreto nei sotterranei del castello di Neil che porta al suo laboratorio principale sul fondo del lago. Nonostante le pareti del tunnel siano fatte di un materiale trasparente simile al vetro, non si riesce a osservare chiaramente il fondale del bacino a causa delle sostanze con cui è stato contaminato."}
________COF_TRO___STR__ = {"ita": u"   Bauli trovati: %i/%i"}
OGGETTI_SPECIALI = {"ita": u"Oggetti speciali"}
PERSONE_INCONTRATE = {"ita": u"Persone incontrate"}
NEMICI_INCONTRATI = {"ita": u"Nemici incontrati"}
GUIDA_COMANDI = {"ita": u"Guida comandi"}
BIC_CON_ACQ = {"ita": u"Bicchiere con acqua"}
CHI_DEL_RIP = {"ita": u"Chiave del ripostiglio"}
CHI_STA_CAS_DI_DAV = {"ita": u"Chiave stanza casa di David"}
CER_DI_RES = {"ita": u"Certificato di residenza"}
IMPOPIETRA = {"ita": u"Impopietra"}
CHI_STA_CAS_DI_NEI = {"ita": u"Chiave stanza castello di Neil"}
LISTA_STRUMENTI = {"ita": u"Lista strumenti"}
CHI_AVA_DI_ROD = {"ita": u"Chiave avamposto di Rod"}
STR_DI_ROD = {"ita": u"Strumenti di Rod"}
CHI_UFF_DI_NEI = {"ita": u"Chiave ufficio di Neil"}
CHI_DEL_SEM = {"ita": u"Chiave del seminterrato"}
IL_BIC_DAC_CHE_HO_CHI_A_HAN_PER_ME_LO_STO_POR_DIE = {"ita": u"Il bicchiere d'acqua che ho chiesto a Hans. Perché me lo sto portando dietro?"}
LA_CHI_DEL_RIP_DEI_MIE_GEN_CI_SON_UN_SAC_DI_COS_INT_L_DEN = {"ita": u"La chiave del ripostiglio dei miei genitori. Ci sono un sacco di cose interessanti là dentro."}
LA_CHI_DEL_MIA_STA_A_CAS_DI_DAV_CRE_CI_SIA_MOL_ALT_STA_DIS_PER_NON_LE_UTI_AL_POS_DI_AMM_TUT_AGL_ALL_PRO = {"ita": u"La chiave della mia stanza a casa di David. Credo ci siano molte altre stanze disponibili... perché non le utilizzano al posto di ammassare tutti agli alloggi profughi?"}
DOC_CHE_DIM_LA_MIA_PER_IN_CIT_NON_CAP_PER_CE_NE_SIA_BIS_NON_BAS_LA_MIA_PRE_PER_DIM_LA_MIA_PER_IN_CIT = {"ita": u"Documento che dimostra la mia permanenza in città. Non capisco perché ce ne sia bisogno... non basta la mia presenza per dimostrare la mia permanenza in città?"}
UNA_STR_PIE_CHE_SIL_PRE_IL_PIC_PUL_CHE_SI_TRO_NEL_PAR_SUP_NON_HO_BEN_CAP_PER_MA_IMP__ATT_QUA_IPN_DAL_SUA_LUC = {"ita": u"Una strana pietra che s'illumina premendo il piccolo pulsante che si trova nella parte superiore. Non ho ben capito perché, ma Impo è attratto quasi ipnoticamente dalla sua luce."}
LA_CHI_DEL_CAM_DA_LET_CHE_MI_HAN_ASS_NEL_CAS_DI_NEI = {"ita": u"La chiave della camera da letto che mi hanno assegnato nel castello di Neil."}
QUE_BUS_CON_LA_LIS_DEG_STR_NEC_PER_STU_IMP_NEI_MI_HA_INC_DI_RIC_A_ROD = {"ita": u"Questa busta contiene la lista degli strumenti necessari per studiare Impo. Neil mi ha incaricata di richiederli a Rod."}
LA_CHI_DEL_DI_ROD_LHO_TRO_IN_MEZ_ALL_SUE_CIA = {"ita": u"La chiave dell'avamposto di Rod. L'ho trovata in mezzo alle sue cianfrusaglie."}
GLI_STR_NEC_PER_STU_IMP_ROD_ERA_SOR_QUA_GLI_HO_MOS_LA_LIS_PER_QUA_MOT_NON_SI_ASP_CHE_NEI_LI_AVR_RIC_A_LUI = {"ita": u"Gli strumenti necessari per studiare Impo. Rod era sorpreso quando gli ho mostrato la lista... per qualche motivo non si aspettava che Neil li avrebbe richiesti a lui."}
LA_CHI_DEL_DI_NEI_ERA_DI_UN_SOL_IO_MI_SON_SOL_DIF = {"ita": u"La chiave dell'ufficio di Neil. Era di un soldato. Io mi sono solo difesa..."}
LA_CHI_DI_UNA_STA_NEL_SEM_DEL_PAL_DI_ROD_LHO_TRO_IN_MEZ_A_DEI_SUO_APP = {"ita": u"La chiave di una stanza nel seminterrato del palazzo di Rod. L'ho trovata in mezzo a dei suoi appunti."}
HANS = {"ita": u"Hans"}
NORM = {"ita": u"Norm"}
TERESA = {"ita": u"Teresa"}
LINO = {"ita": u"Lino"}
SOLDATO_DECEDUTO = {"ita": u"Soldato deceduto"}
DAVID = {"ita": u"David"}
OLIVIA = {"ita": u"Olivia"}
RAGAZZO_STRANO = {"ita": u"Ragazzo strano"}
ROD = {"ita": u"Rod"}
RODOLFO = {"ita": u"Rodolfo"}
RALLO = {"ita": u"Rallo"}
BIBLIOTECARIO = {"ita": u"Bibliotecario"}
REN = {"ita": u"René"}
IMPO = {"ita": u"Impo"}
NEIL = {"ita": u"Neil"}
PAPPAGALLO = {"ita": u"Pappagallo"}
PAPPALIBROSONORO = {"ita": u"Pappa-Libro Sonoro"}
COSTRUTTORE = {"ita": u"Costruttore"}
SARA = {"ita": u"Sara"}
MIO_FRA_MI_PIA_STA_CON_LUI_ANC_SE_IN_QUE_PER__SEM_PI_PEN_E_IRR_FOR_SUC_CRE_MIO_PAD_DIC_CHE_SI_STA_RI = {"ita": u"Mio fratello. Mi piace stare con lui, anche se in questo periodo è sempre più pensieroso e irritabile. Forse succede crescendo... Mio padre dice che si sta \"rincoglionendo\"."}
IL_PAD_IL_GOV_IL_CAP_SUP_DEL_FAM_MIO_PAD_IO_E_HAN_DO_ANC_CRE_QUI__LUI_LUN_ILL_DA_DIO_PER_PRE_LE_SCE_GIU_PER_TUT = {"ita": u"Il padrone, il governante, il capo supremo della famiglia: mio padre. Io e Hans \"dobbiamo ancora crescere\", quindi è lui l'unico illuminato da Dio per prendere le scelte giuste per tutti."}
MIA_MAD_ASC_E_RIP_QUE_CHE_DIC_MIO_PAD_MI_SEN_UN_PO_STU_E_ARR_ORA_CHE_LHO_PUR_SCR_A_PAR_QUE_SI_PRE_CUR_DEL_CAS_E_AMA_LA_SUA_FAM = {"ita": u"Mia madre. Ascolta e ripete quello che dice mio padre. Mi sento un po' stupida e arrogante ora che l'ho pure scritto... A parte questo, si prende cura della casa e ama la sua famiglia."}
LIN_MIO_PAD_LHA_POR_A_CAS_CIR_5_ANN_FA_QUA_ERA_ANC_UN_CUC_ADE__BEN_ADD_PER_LA_CAC_E_PER_TEN_LON_I_MAL = {"ita": u"Linooo... Mio padre l'ha portato a casa circa 5 anni fa quando era ancora un cucciolo. Adesso è ben addestrato per la caccia e per tenere lontani i malintenzionati."}
UN_SOL_CHE_HO_TRO_A_TER_MAR_NEL_FOR_CAD_LAR_CHE_GLI_HO_PRE_LO_TEN_PI_O_MEN_INS_ME_NE_SON_ACC_TRO_TAR = {"ita": u"Un soldato che ho trovato a terra martoriato nella Foresta Cadetta. L'armatura che gli ho preso lo teneva più o meno insieme... me ne sono accorta troppo tardi..."}
QUE_SOL_NEL_FOR_ERA_IL_FIG_DI_DAV_E_OLI_NON_AVR_DOV_RUB_LAR = {"ita": u"Quel soldato nella foresta era il figlio di David e Olivia. Non avrei dovuto rubargli l'armatura..."}
IL_CA_DEL_GUA_NOT_MI_HA_FAT_ENT_IN_CIT_NON_NON_CI_FOS_PI_SPA_PER_ALT_PRO_HA_DET_CHE_MI_OSP_IN_CAS_SUA = {"ita": u"Il \"Capitano della guardia notturna\". Mi ha fatta entrare in città nonostante non ci fosse più spazio per altri profughi. Ha detto che mi ospiterà in casa sua."}
IL_CAP_DEL_GUA_NOT_MI_HA_OSP_SOL_PER_VOL_CHE_GLI_PAR_DEL_SOL_MOR_NEL_FOR_SUO_FIG_HA_ANC_PAR_DI_UNA_GUE_IN_COR = {"ita": u"Il capitano della guardia notturna. Mi ha ospitata solo perché voleva che gli parlassi del soldato morto nella foresta, suo figlio... Ha anche parlato di una guerra in corso..."}
MOG_DI_DAV_E_MAD_DEL_SOL_A_CUI_HO_RUB_LAR_ERA_VIS_SCO_DUR_LA_CEN_ALL_FIN_SE_N_AND_SEN_DIR_UNA_PAR = {"ita": u"Moglie di David e madre del soldato a cui ho rubato l'armatura. Era visibilmente sconvolta durante la cena. Alla fine se n'è andata senza dire una parola."}
MOG_DI_DAV_HA_DEC_DI_SUI_POS_CHE_PER_LEI_NON_AVE_SEN_VIV_SE_NON_PER_SUO_FIG_COS_AVR_FAT_SE_NON_NE_AVE_MAI_AVU_UNO = {"ita": u"Moglie di David. Ha deciso di suicidarsi... Possibile che per lei non aveva senso vivere se non per suo figlio? Cosa avrebbe fatto se non ne avesse mai avuto uno?"}
UN_TIP_STR_CHE_HO_TRO_IN_CIT_SI_GUA_INT_DI_CON_MA_IL_SUO_SGU_RIC_CON_SU_UNA_RAG_POC_DIS_MI_HA_AIU_A_TRO_GLI_ALL = {"ita": u"Un tipo strano che ho trovato in città. Si guardava intorno di continuo, ma il suo sguardo ricadeva continuamente su una ragazza poco distante. Mi ha aiutata a trovare gli alloggi."}
UN_TIP_LOS_A_CUI_HO_DAT___STR__U_MON_PER_ENT_NEL_SUA_CO_COM_SAR_NON_SEM_MOL_AFF_MA_POT_RIV_UTI_IN_CAS_DI_NEC_SPE = {"ita": u"Un tipo losco a cui ho dato %i monete per entrare nella sua \"confraternita\"... complimenti Sara. Non sembra molto affidabile, ma potrebbe rivelarsi utile in caso di necessità. Spero..."}
SI_FA_CHI_ROD_PEN_NON_GLI_PIA_IL_SUO_NOM_COM_POT_CHI_SOL_OL_NON_SEM_MOL_AFF_MA_DEV_DIR_CHE_SI__RIV_UTI_IN_DIV_OCC = {"ita": u"Si fa chiamare Rod, penso non gli piaccia il suo nome completo. Potrei chiamarlo solo \"Olfo\"... Non sembra molto affidabile, ma devo dire che si è rivelato utile in diverse occasioni."}
PEN_NON_GLI_PIA_IL_SUO_NOM_QUI_SI_FA_CHI_RO_O_SEM_OL_NON_SEM_MOL_AFF_MA_DEV_DIR_CHE_SI__RIV_UTI_IN_DIV_OCC = {"ita": u"Penso non gli piaccia il suo nome, quindi si fa chiamare \"Rod\" o semplicemente \"Olfo\". Non sembra molto affidabile, ma devo dire che si è rivelato utile in diverse occasioni."}
UNO_STR_IND_CHE_HO_TRO_IN_CIT_PAR_IN_MAN_ASS_E_AVE_LO_SGU_PER_NEL_VUO = {"ita": u"Uno strano individuo che ho trovato in città. Parlava in maniera assurda e aveva lo sguardo perso nel vuoto."}
UNO_STR_IND_CHE_HO_TRO_IN_CIT_PAR_IN_MAN_ASS_E_AVE_LO_SGU_PER_NEL_VUO_MI_HA_PRO_DI_PAR_AL_TES_SO_PAZ_O_SON_RAL = {"ita": u"Uno strano individuo che ho trovato in città. Parlava in maniera assurda e aveva lo sguardo perso nel vuoto. Mi ha proposto di partecipare al test \"Sono Pazzo o sono Rallo\"."}
IL_SUO_NOM_DOV_ESS_RA_ANC_SE_OGN_VOL_LO_PRO_DIV_D_LIM_DI_ESS_UN_PAZ_MA__COS_DI_QUE_CHE_GLI_ACC_SI__RIC_DI_ME = {"ita": u"Il suo nome dovrebbe essere \"Rallo\", anche se ogni volta lo pronuncia diversamente. Dà l'impressione di essere un pazzo, ma è cosciente di quello che gli accade: si è ricordato di me."}
GES_LA_BIB_IN_CIT_HA_DEC_DI_AIU_NON_FOS_STA_ABB_MOL_POI_GLI_HO_PUR_VOM_NEL_STU_COM_FA_AD_AVE_COS_TAN_PAZ = {"ita": u"Gestisce la biblioteca in città. Ha deciso di aiutarmi nonostante fossi stata abbastanza molesta. Poi gli ho pure vomitato nello studio... Come fa ad avere così tanta pazienza?"}
GES_LA_BIB_IN_CIT__UNA_PER_MOL_INT_LE_SUE_TEO_SUL_REA_SON_ABB_SCO_SOP_PER_SON_INC_SEN = {"ita": u"Gestisce la biblioteca in città. È una persona molto interessante, le sue teorie sulla realtà sono abbastanza sconvolgenti soprattutto perché sono incredibilmente sensate."}
LA_SCR_IM__INC_SUL_NUC_DI_TUT_GLI_ANI_DI_QUE_SPE_ASS__LUL_DEL_SUA_SPE_GLI_ALT_SI_SON_EST_POC_PRI_CHE_IL_LAG_SI_CON = {"ita": u"La scritta \"Impo\" è incisa sulla nuca di tutti gli animali di questa specie, assurdo! È l'ultimo della sua specie, gli altri si sono estinti poco prima che il lago si contaminasse."}
MOL_PRO_SON_STA_PRO_DAL_COS_LA_LOR_FUN__QUE_DI_MAN_IN_ATT_IL_CAL_NEL_VUL_E_PRO_CI_CHE_QUE_RIC = {"ita": u"Molto probabilmente sono stati progettati dal Costruttore. La loro funzione è quella di mantenere in attività il calcolatore nel vulcano e produrre ciò che quest'ultimo richiede."}
UN_POT_CHE_A_DET_DI_REN_CON_GLI_SPO_DI_TUT_LA_REG_CHE_SIA_STA_DEL_DAL_CIT_NON_IMP_SPE_CHE_POT_AIU_CON_HAN = {"ita": u"Un potente che, a detta di René, controlla gli spostamenti di tutta la regione. Che sia stato delegato dall'autorità cittadina? Non importa, spero che potrà aiutarmi con Hans."}
_ALT_DUE_MET_HA_LA_PEL_PAL_E_I_SUO_OCC_SON_SPR_CRE_SI_SIA_FAT_DEL_OPE_PER_DIV_COS_A_QUA_PAR_HA_CEN = {"ita": u"È alto due metri, ha la pelle pallidissima e i suoi occhi sono sproporzionati. Credo si sia fatto delle operazioni per diventare così. A quanto pare ha centosettant'anni."}
UN_PAP_PAR_CHE_VEN_LE_STE_MER_DI_ROD_CHE_FAC_PAR_DEL_SUA_CO_GLI__BAS_VED_PER_RIC_E_DAR_LAC_AL_CAT = {"ita": u"Un pappagallo parlante che vende le stesse merci di Rod. Che faccia parte della sua \"confraternita\"? Gli è bastato vedermi per riconoscermi e darmi l'accesso al catalogo..."}
UN_PAP_PAR_ADD_DA_ROD_PER_VEN_MER_DA_QUE_CHE_HO_CAP_MI_D_LAC_AL_CAT_PER_SON_STA_IN_QUA_MOD_ASS_A_UN_SUO_RIC = {"ita": u"Un pappagallo parlante addestrato da Rod per vendere merci. Da quello che ho capito, mi dà l'accesso al catalogo perché sono stata in qualche modo associata a un suo ricordo..."}
_UN_TIZ_CHE_HO_TRO_MOR_DEN_UNA_CEL_NEL_CAV_IMP_IND_UNA_STR_TUT_E_HA_DEI_TUB_CHE_GLI_ESC_DAL_COR_MI_DOM_COS_CI_FAC_L_DEN = {"ita": u"È un tizio che ho trovato morto dentro una cella nella Caverna Impo. Indossa una strana tuta e ha dei tubi che gli escono dal corpo. Mi domando cosa ci facesse lì dentro..."}
LUI__COL_CHE_HA_MAN_APE_E_IN_EQU_IL_CON_TRA_NOI_E_IL_NEM_NEI_IPO_CHE_VOL_IMP_ALL_DEL_RIC_INT_E_CON_IN_AMB_BEL = {"ita": u"Lui è colui che ha mantenuto aperto e in equilibrio il conflitto tra noi e il Nemico. Neil ipotizzava che volesse imporre all'uomo delle ricerche intensive e continue in ambito bellico."}
POT_POR_AVA_LE_RIC_DI_ROD_MA_CHE_SEN_HA_SON_ANC_IO_BR_FOR_NON_HA_SEN_NEA_POR_IL_PRO = {"ita": u"Potrei portare avanti le ricerche di Rod, ma che senso ha? Sono ancora io? <br> Forse non ha senso neanche porsi il problema."}
ORCO = {"ita": u"Orco"}
PIPISTRELLO = {"ita": u"Pipistrello"}
TARTARUGA_VERDE = {"ita": u"Tartaruga verde"}
TARTARUGA_MARRONE = {"ita": u"Tartaruga marrone"}
LUPO_GRIGIO = {"ita": u"Lupo grigio"}
LUPO_BIANCO = {"ita": u"Lupo bianco"}
LUPO_NERO = {"ita": u"Lupo nero"}
CINGHIALE = {"ita": u"Cinghiale"}
AGGRESSORE_1 = {"ita": u"Aggressore 1"}
AGGRESSORE_2 = {"ita": u"Aggressore 2"}
SERPENTE_VERDE = {"ita": u"Serpente verde"}
SERPENTE_ARANCIONE = {"ita": u"Serpente arancione"}
RAGNO_NERO = {"ita": u"Ragno nero"}
RAGNO_ROSSO = {"ita": u"Ragno rosso"}
SCORPIONE = {"ita": u"Scorpione"}
GUFO_MARRONE = {"ita": u"Gufo marrone"}
GUFO_BIANCO = {"ita": u"Gufo bianco"}
STRUZZO = {"ita": u"Struzzo"}
CASUARIO = {"ita": u"Casuario"}
FALCO = {"ita": u"Falco"}
AQUILA = {"ita": u"Aquila"}
SER_CON_SPA = {"ita": u"Servo con spada"}
SER_CON_ARC = {"ita": u"Servo con arco"}
SER_CON_LAN = {"ita": u"Servo con lancia"}
IMPO_LEGGERO = {"ita": u"Impo leggero"}
IMPO_VOLANTE = {"ita": u"Impo volante"}
IMPO_PESANTE = {"ita": u"Impo pesante"}
IMP_VOL_PES = {"ita": u"Impo volante pesante"}
IMPO_TORRE = {"ita": u"Impo torre"}
DEI_GIG_ORC_CHE_IMP_ENO_SPA_MIO_PAD_NE_PAR_SPE_E_HO_NOT_CHE_A_VOL_ALC_RAC_SI_CON_TRA_LOR_FOR_NON_ESI_VER = {"ita": u"Dei giganteschi orchi che impugnano enormi spadoni. Mio padre ne parla spesso e ho notato che a volte alcuni racconti si contraddicono tra loro... forse non esistono veramente."}
DEI_PIP_VEL_NON_LI_HO_MAI_VIS_AL_DI_FUO_DEI_MIE_INC_QUI_ANC_QUE_POT_ESS_UNA_INV_DI_MIO_PAD_PER_NON_FAR_AND_NEL_FOR = {"ita": u"Dei pipistrelli velenosi. Non li ho mai visti al di fuori dei miei incubi, quindi anche questi potrebbero essere un'altra invenzione di mio padre per non farmi andare nella foresta."}
CRE_OST_CHE_SI_TRO_NEL_FOR_CAD_NON__MOL_PER_IN_QUA_SI_MUO_MOL_LEN_E_I_SUO_MOR_NON_SON_PER_NIE_DOL = {"ita": u"Creatura ostile che si trova nella Foresta Cadetta. Non è molto pericolosa in quanto si muove molto lentamente e i suoi morsi non sono per niente dolorosi."}
CRE_OST_CHE_SI_TRO_NEL_FOR_CAD_UN_PO_PI_FOR_DEL_TAR_VER_MA_NIE_DI_TRO_PRE_SI_MUO_LEN = {"ita": u"Creatura ostile che si trova nella Foresta Cadetta. Un po' più forte della Tartaruga verde, ma niente di troppo preoccupante. Si muove lentamente."}
CRE_OST_CHE_SI_TRO_NEL_FOR_CAD_LIN_UN_TUO_SIM_UN_LUP_ABB_AGG_MA_POC_RES__ABB_VEL_NON_FAC_DA_SEM = {"ita": u"Creatura ostile che si trova nella Foresta Cadetta. Linooo... un tuo simile. Un lupo abbastanza aggressivo ma poco resistente. È abbastanza veloce, non facile da seminare."}
CRE_OST_CHE_SI_TRO_NEL_FOR_CAD__UN_PO_PI_FOR_E_RES_DEL_LUP_GRI_QUE_POC_SEC_IN_CUI_TI_FIS_PRI_DI_ATT_SON_GEL = {"ita": u"Creatura ostile che si trova nella Foresta Cadetta. È un po' più forte e resistente del Lupo grigio. Quei pochi secondi in cui ti fissa prima di attaccarti sono gelanti."}
CRE_OST_CHE_SI_TRO_NEL_FOR_CAD_LA_RAZ_DI_LUP_PI_FOR_NEL_BUI_DEL_FOR_SAR_DIF_NOT_SE_NON_VIA_IN_BRA = {"ita": u"Creatura ostile che si trova nella Foresta Cadetta. La razza di lupo più forte. Nel buio della foresta, sarebbe difficile notarli se non viaggiassero in branco."}
CRE_OST_CHE_SI_TRO_NEL_FOR_CAD__UN_BES_GRA_IL_DOP_DI_ME_NE_HO_DOV_AFF_UNO_E_PER_POC_NON_CI_RIM_SEC_COM_QUE_SOL = {"ita": u"Creatura ostile che si trova nella Foresta Cadetta. È un bestione grande il doppio di me. Ne ho dovuto affrontare uno e per poco non ci rimanevo secca come quel soldato..."}
NON_VOL_UCC_AVE_UN_TON_VIO_MI_AVR_STU_FOR_SAR_STA_MEG_NON_OPP = {"ita": u"Non volevo ucciderlo. Aveva un tono violento, mi avrebbe stuprata... forse sarebbe stato meglio non opporsi...?"}
LHO_UCC_PRI_CHE_POT_TOC_NON_SON_UNA_PAZ_ASS_VOL_CHI_FAR_DEL_MAL_CHE_CAZ_HO_FAT = {"ita": u"L'ho ucciso prima che potesse toccarmi. Non sono una pazza assassina, voleva chiaramente farmi del male... che cazzo ho fatto..."}
CRE_OST_CHE_SI_TRO_NEL_SEL_ARI_LI_ODI_FAN_TRO_CON_CON_I_LOR_SON_SI_MUO_LEN_FIN_NON_TRO_UNA_PRE_POI_ACC_DI_COL = {"ita": u"Creatura ostile che si trova nella Selva Arida. Li odio, fanno troppa confusione con i loro sonagli! Si muovono lentamente finché non trovano una preda, poi accelerano di colpo."}
CRE_OST_CHE_SI_TRO_NEL_SEL_ARI_QUE_MAL_SON_VEL_SEM_MUO_LEN_MA_QUA_AVV_LA_PRE_SON_FUL_NEL_RAG = {"ita": u"Creatura ostile che si trova nella Selva Arida. Questi maledetti sono velenosi! Sembrano muoversi lentamente ma, quando avvistano la preda, sono fulminei nel raggiungerla."}
CRE_OST_CHE_SI_TRO_NEL_SEL_ARI_SON_ENO_VEL_E_ABB_RES_I_LOR_MOR_FAN_ABB_MAL_MA_PER_FOR_NON_SON_VEL = {"ita": u"Creatura ostile che si trova nella Selva Arida. Sono enormi, veloci e abbastanza resistenti. I loro morsi fanno abbastanza male, ma per fortuna non sono velenosi."}
CRE_OST_CHE_SI_TRO_NEL_SEL_ARI_QUE_SON_VER_I_PI_FAS_ATT_A_DIS_LAN_LA_LOR_SAL_VEL_PER_FOR_NON_SON_MOL_RES = {"ita": u"Creatura ostile che si trova nella Selva Arida. Questi sono veramente i più fastidiosi. Attaccano a distanza lanciando la loro saliva velenosa. Per fortuna non sono molto resistenti."}
CRE_OST_CHE_SI_TRO_NEL_SEL_ARI_SEN_DUB_LA_BEL_PI_TEM_DEL_POS__FOR_VEL_RES_E_PUR_VEL_IMP_AFF_IN_BRA = {"ita": u"Creatura ostile che si trova nella Selva Arida. Senza dubbio la belva più temibile del posto. È forte, veloce, resistente e pure velenoso... Impossibile affrontarli in branco."}
CRE_OST_CHE_SI_TRO_NEL_PAS_MON_QUE_GUF_SEM_TAN_INN_E_AMI_MA_APP_TI_VED_TI_PIO_ADD_E_INI_AD_ART_SEN_SOS = {"ita": u"Creatura ostile che si trova nel Passo Montano. Questi gufetti sembrano tanto innocui e amichevoli, ma, appena ti vedono, ti piombano addosso e iniziano ad artigliarti senza sosta."}
CRE_OST_CHE_SI_TRO_NEL_PAS_MON_A_PRI_IMP_ANC_LOR_INN_E_AMI_MA_COM_I_LOR_SIM_GUF_MAR_SON_OST_E_PER_PI_AGG_E_RES = {"ita": u"Creatura ostile che si trova nel Passo Montano. A primo impatto, anche loro innocui e amichevoli, ma, come i loro simili gufi marroni, sono ostili e persino più aggressivi e resistenti."}
CRE_OST_CHE_SI_TRO_NEL_PAS_MON_DEG_STR_VOL_CHE_PER_NON_HO_MAI_VIS_VOL_IMM_NON_POS_PER_LA_LOR_STA_SON_UN_PO_GOF_MA_MOL_FOR = {"ita": u"Creatura ostile che si trova nel Passo Montano. Degli strani volatili che però non ho mai visto volare... immagino non possano per la loro stazza. Sono un po' goffi, ma molto forti."}
CRE_OST_CHE_SI_TRO_NEL_PAS_MON_DEG_STR_UN_PO_PI_BAS_TOZ_E_VEL_LE_LOR_PIU_NER_SON_UNT_E_APP_NON__BEL_VED_ARR_ADD = {"ita": u"Creatura ostile che si trova nel Passo Montano. Degli struzzi un po' più bassi, tozzi e velenosi. Le loro piume nere sono unte e appiccicose, non è bello vederseli arrivare addosso."}
CRE_OST_CHE_SI_TRO_NEL_PAS_MON_UNO_DEI_VOL_PI_TEM_LA_LOR_APE_ALA_MIS_QUA_IL_DOP_DEL_MIA_ALT_SON_VEL_AGG_E_MOL_RES = {"ita": u"Creatura ostile che si trova nel Passo Montano. Uno dei volatili più temibili. La loro apertura alare misura quasi il doppio della mia altezza. Sono veloci, aggressivi e molto resistenti."}
CRE_OST_CHE_SI_TRO_NEL_PAS_MON_LA_PI_PER_DEL_ZON__GRA_CIR_QUA_UN_FAL_MA__PI_FER_E_RES_FOR_NON_SI_INC_SPE = {"ita": u"Creatura ostile che si trova nel Passo Montano. La più pericolosa della zona. È grande circa quanto un falco, ma è più feroce e resistente. Fortunatamente non si incontra spesso."}
SOL_DI_NEI_A_GUA_DEL_CAS_IL_SUO_COM__STA_IMM_IN_UN_PUN_DEL_CAS_CAP_DI_INF_ING_DAN_DAT_LA_SUA_ABI_NEL_DEL_SPA = {"ita": u"Soldato di Neil a guardia del castello. Il suo compito è stare immobile in un punto del castello. Capace di infliggere ingenti danni data la sua abilità nell'utilizzo della spada."}
SOL_DI_NEI_A_GUA_DEL_CAS_IL_SUO_COM__STA_IMM_IN_UN_PUN_DEL_CAS_SPE_NEL_DEL_ATT_DI_CON_IL_NEM_DAL_DIS = {"ita": u"Soldato di Neil a guardia del castello. Il suo compito è stare immobile in un punto del castello. Specializzato nell'uso dell'arco, attacca di continuo il nemico dalla distanza."}
SOL_DI_NEI_A_GUA_DEL_CAS_IL_SUO_COM__STA_IMM_IN_UN_PUN_DEL_CAS_USA_UNA_LUN_LAN_NON_PAR_EFF_MA_PRE_DI_VEL = {"ita": u"Soldato di Neil a guardia del castello. Il suo compito è stare immobile in un punto del castello. Usa una lunga lancia non particolarmente efficace, ma pregna di veleno."}
CRE_OST_CHE_SI_TRO_NEL_CAV_IMP_VAG_IN_GIR_ACC_IMP_CHE_RIC_SCA_NEL_ROC_DEL_CAV_NEL_ROC_NON_PIA_NON_SON_FR = {"ita": u"Creatura ostile che si trova nella Caverna Impo. Vaga in giro accumulando impofrutti che ricava scavando nelle rocce della caverna. Nelle rocce, non piante... non sono \"frutti\"!"}
CRE_OST_CHE_SI_TRO_NEL_CAV_IMP_SOR_LA_ZON_MEN_GLI_ALT_IMP_RAC_IMP_CRE_CHE_SIA_SUO_COM_ANC_IND_AGL_ALT_DOV_SCA = {"ita": u"Creatura ostile che si trova nella Caverna Impo. Sorveglia la zona mentre gli altri impo raccolgono impofrutti. Credo che sia suo compito anche indicare agli altri dove scavare."}
CRE_OST_CHE_SI_TRO_NEL_CAV_IMP_COM_GLI_IMP_LEG_RIC_IMP_DAL_ROC_DEL_CAV__PI_GRO_E_LEN_DEG_ALT_MA__IN_GRA_DI_TRA_PI_MAT = {"ita": u"Creatura ostile che si trova nella Caverna Impo. Come gli impo leggeri, ricava impofrutti dalle rocce della caverna. È più grosso e lento degli altri, ma è in grado di trasportare più materiale."}
CRE_OST_CHE_SI_TRO_NEL_CAV_IMP_COM_I_NOR_IMP_VOL_SOR_LA_ZON_MEN_GLI_ALT_RAC_IMP__PI_GRO_E_LEN_DEG_ALT_MA_MOL_PI_FOR = {"ita": u"Creatura ostile che si trova nella Caverna Impo. Come i normali impo volanti, sorveglia la zona mentre gli altri raccolgono impofrutti. È più grosso e lento degli altri, ma molto più forte."}
CRE_OST_CHE_SI_TRO_NEL_CAV_IMP_NON_HA_UN_RUO_EFF_NEL_RAC_DEG_IMP_SE_NON_QUE_DI_PRO_GLI_ALT__LEN_MA_QUA_COL_FA_PAR_MAL = {"ita": u"Creatura ostile che si trova nella Caverna Impo. Non ha un ruolo effettivo nella raccolta degli impofrutti se non quello di proteggere gli altri. È lento, ma quando colpisce fa parecchio male."}
TAS_MOD_MOV = {"ita": u"Tastiera: Mod. movimento"}
TAS_MOD_INT = {"ita": u"Tastiera: Mod. interazione"}
TASTIERA_MENU = {"ita": u"Tastiera: Menu"}
MOU_MOD_MOV = {"ita": u"Mouse: Mod. movimento"}
MOU_MOD_INT = {"ita": u"Mouse: Mod. interazione"}
MOUSE_MENU = {"ita": u"Mouse: Menu"}
CON_MOD_MOV = {"ita": u"Controller: Mod. movimento"}
CON_MOD_INT = {"ita": u"Controller: Mod. interazione"}
CONTROLLER_MENU = {"ita": u"Controller: Menu"}
CONDIZIOIMPOFOGLI = {"ita": u"Condizio-Impofoglie"}
TOGLI_CONDIZIOIMPOFOGLIO = {"ita": u"Togli Condizio-Impofoglia"}
TOGLI_CONDIZIOIMPOFOGLIO_ = {"ita": u"Togli Condizio-Impofoglia:"}
TOG_IL_CON_DAL_CEL_DI_MEM = {"ita": u"Togli la Condizio-Impofoglia dalla cella di memoria."}
SAR_CON_PV__80_ = {"ita": u"Sara con <*>#italic#PV<*> < 80%:"}
ESE_LAZ_SU_SAR_SE_LA_VED_E_HA_PV__80 = {"ita": u"Esegue l'azione su Sara se la vede e ha <*>#italic#PV<*> < 80%."}
SCONOSCIUTA = {"ita": u"Sconosciuta"}
SAR_CON_PV__50_ = {"ita": u"Sara con <*>#italic#PV<*> < 50%:"}
ESE_LAZ_SU_SAR_SE_LA_VED_E_HA_PV__50 = {"ita": u"Esegue l'azione su Sara se la vede e ha <*>#italic#PV<*> < 50%."}
SAR_CON_PV__30_ = {"ita": u"Sara con <*>#italic#PV<*> < 30%:"}
ESE_LAZ_SU_SAR_SE_LA_VED_E_HA_PV__30 = {"ita": u"Esegue l'azione su Sara se la vede e ha <*>#italic#PV<*> < 30%."}
SAR_CON_VEL_ = {"ita": u"Sara con veleno:"}
ESE_LAZ_SU_SAR_SE_LA_VED_ED__AVV = {"ita": u"Esegue l'azione su Sara se la vede ed è avvelenata."}
SEM_A_SAR_ = {"ita": u"Sempre a Sara:"}
ESE_LAZ_SU_SAR_IN_CON_QUA_LA_VED_SE_LAZ_ASS_COM_UNA_DI_STA_VIE_ESE_SOL_SE_LO_STA_NON__ATT = {"ita": u"Esegue l'azione su Sara in continuazione quando la vede (se l'Azio-Impofoglia associata comporta un'alterazione di stato, viene eseguita solo se lo status non è attivo)."}
IMP_CON_PE__80_ = {"ita": u"Impo con <*>#italic#PE<*> < 80%:"}
ESE_LAZ_SU_IMP_QUA_HA_PE__80 = {"ita": u"Esegue l'azione su Impo quando ha <*>#italic#PE<*> < 80%."}
IMP_CON_PE__50_ = {"ita": u"Impo con <*>#italic#PE<*> < 50%:"}
ESE_LAZ_SU_IMP_QUA_HA_PE__50 = {"ita": u"Esegue l'azione su Impo quando ha <*>#italic#PE<*> < 50%."}
IMP_CON_PE__30_ = {"ita": u"Impo con <*>#italic#PE<*> < 30%:"}
ESE_LAZ_SU_IMP_QUA_HA_PE__30 = {"ita": u"Esegue l'azione su Impo quando ha <*>#italic#PE<*> < 30%."}
IMPO_SURRISCALDATO_ = {"ita": u"Impo surriscaldato:"}
ESE_LAZ_SU_IMP_QUA__SUR = {"ita": u"Esegue l'azione su Impo quando è surriscaldato."}
SEM_A_IMP_ = {"ita": u"Sempre a Impo:"}
ESE_LAZ_SU_IMP_IN_CON_SE_LAZ_ASS_COM_UNA_DI_STA_VIE_ESE_SOL_SE_LO_STA_NON__ATT = {"ita": u"Esegue l'azione su Impo in continuazione (se l'Azio-Impofoglia associata comporta un'alterazione di stato, viene eseguita solo se lo status non è attivo)."}
NEM_A_CAS_ = {"ita": u"Nemico a caso:"}
ESE_LAZ_SU_UN_NEM_A_CAS = {"ita": u"Esegue l'azione su un nemico a caso."}
NEMICO_VICINO_ = {"ita": u"Nemico vicino:"}
ESE_LAZ_SU_UN_NEM_IN_UNA_CAS_ACC_ALL_PRO = {"ita": u"Esegue l'azione su un nemico in una casella accanto alla propria."}
NEMICO_LONTANO_ = {"ita": u"Nemico lontano:"}
ESE_LAZ_SU_UN_NEM_DIS_DI_ALM_UNA_CAS_IN_CAS_DI_MOL_BER_ESE_LAZ_SU_QUE_PI_VIC = {"ita": u"Esegue l'azione su un nemico distante di almeno una casella (in caso di molteplici bersagli, esegue l'azione su quello più vicino)."}
NEM_CON_PV__80_ = {"ita": u"Nemico con <*>#italic#PV<*> < 80%:"}
ESE_LAZ_SU_UN_NEM_CON_PV__80_IN_CAS_DI_MOL_BER_ESE_LAZ_SU_QUE_PI_VIC = {"ita": u"Esegue l'azione su un nemico con <*>#italic#PV<*> < 80% (in caso di molteplici bersagli, esegue l'azione su quello più vicino)."}
NEM_CON_PV__50_ = {"ita": u"Nemico con <*>#italic#PV<*> < 50%:"}
ESE_LAZ_SU_UN_NEM_CON_PV__50_IN_CAS_DI_MOL_BER_ESE_LAZ_SU_QUE_PI_VIC = {"ita": u"Esegue l'azione su un nemico con <*>#italic#PV<*> < 50% (in caso di molteplici bersagli, esegue l'azione su quello più vicino)."}
NEM_CON_PV__30_ = {"ita": u"Nemico con <*>#italic#PV<*> < 30%:"}
ESE_LAZ_SU_UN_NEM_CON_PV__30_IN_CAS_DI_MOL_BER_ESE_LAZ_SU_QUE_PI_VIC = {"ita": u"Esegue l'azione su un nemico con <*>#italic#PV<*> < 30% (in caso di molteplici bersagli, esegue l'azione su quello più vicino)."}
NEM_CON_MEN_PV_ = {"ita": u"Nemico con meno <*>#italic#PV<*>:"}
ESE_LAZ_SUL_NEM_CON_MEN_PV_IN_CAS_DI_MOL_BER_ESE_LAZ_SU_QUE_PI_VIC = {"ita": u"Esegue l'azione sul nemico con meno <*>#italic#PV<*> (in caso di molteplici bersagli, esegue l'azione su quello più vicino)."}
NUM_DI_NEM__1_ = {"ita": u"Numero di nemici > 1:"}
ESE_LAZ_QUA_NEI_PAR_C_PI_DI_1_NEM_IN_CAS_DI_AZI_A_BER_SIN_LAZ_VIE_ESE_SUL_NEM_PI_VIC = {"ita": u"Esegue l'azione quando nei paraggi c'è più di 1 nemico (in caso di Azio-Impofoglia a bersaglio singolo, l'azione viene eseguita sul nemico più vicino)."}
NUM_DI_NEM__2_ = {"ita": u"Numero di nemici > 2:"}
ESE_LAZ_QUA_NEI_PAR_CI_SON_PI_DI_2_NEM_IN_CAS_DI_AZI_A_BER_SIN_LAZ_VIE_ESE_SUL_NEM_PI_VIC = {"ita": u"Esegue l'azione quando nei paraggi ci sono più di 2 nemici (in caso di Azio-Impofoglia a bersaglio singolo, l'azione viene eseguita sul nemico più vicino)."}
NUM_DI_NEM__3_ = {"ita": u"Numero di nemici > 3:"}
ESE_LAZ_QUA_NEI_PAR_CI_SON_PI_DI_3_NEM_IN_CAS_DI_AZI_A_BER_SIN_LAZ_VIE_ESE_SUL_NEM_PI_VIC = {"ita": u"Esegue l'azione quando nei paraggi ci sono più di 3 nemici (in caso di Azio-Impofoglia a bersaglio singolo, l'azione viene eseguita sul nemico più vicino)."}
AZIOIMPOFOGLI = {"ita": u"Azio-Impofoglie"}
TOGLI_AZIOIMPOFOGLIO = {"ita": u"Togli Azio-Impofoglia"}
TOGLI_AZIOIMPOFOGLIO_ = {"ita": u"Togli Azio-Impofoglia:"}
TOG_LAZ_DAL_CEL_DI_MEM = {"ita": u"Togli l'Azio-Impofoglia dalla cella di memoria."}
CURA_ = {"ita": u"Cura:"}
CON___STR___PE = {"ita": u"Consumo: %i <*>#italic#PE<*>"}
REC_UN_PO_DI_PV_DI_SAR = {"ita": u"Crea particelle curative che permettono di recuperare qualche <*>#italic#PV<*> di Sara."}
CURA_P_ = {"ita": u"Cura +:"}
REC_MOL_PV_DI_SAR = {"ita": u"Crea particelle curative che permettono di recuperare molti <*>#italic#PV<*> di Sara."}
CURA_PP_ = {"ita": u"Cura ++:"}
REC_UNE_QUA_DEI_PV_DI_SAR = {"ita": u"Crea particelle curative che permettono di recuperare un'enorme quantità di <*>#italic#PV<*> di Sara."}
ANTIDOTO_ = {"ita": u"Antidoto:"}
CUR_AVV_A_SAR_IMP = {"ita": u"Crea una nube di gas medicinale che cura l'avvelenamento a Sara."}
CARICA_ATTACCO_ = {"ita": u"Carica attacco:"}
INC_LAT_DI_SAR_PER_UN_PO_DI_TEM_NON_HA_EFF_SUI_NEM = {"ita": u"Incrementa l'attacco di Sara per un po' di tempo (non ha effetto sui nemici)."}
CARICA_DIFESA_ = {"ita": u"Carica difesa:"}
INC_LA_DIF_DI_SAR_PER_UN_PO_DI_TEM_NON_HA_EFF_SUI_NEM = {"ita": u"Incrementa la difesa di Sara per un po' di tempo (non ha effetto sui nemici)."}
AUTORICARICA_ = {"ita": u"Auto-ricarica:"}
RIC_UN_PO_IMP_MA_RIC_DUE_TUR_E_PRO_SUR_APP_SEM_SU_IMP = {"ita": u"Utilizza un pannello energetico per ricaricarsi un po' di batteria, ma richiede due turni e provoca surriscaldamento (applicata sempre su Impo)."}
AUTORICARICA_P_ = {"ita": u"Auto-ricarica +:"}
RIC_DI_MOL_IMP_MA_RIC_DUE_TUR_E_PRO_SUR_APP_SEM_SU_IMP = {"ita": u"Utilizza un pannello energetico per ricaricarsi di molto la batteria, ma richiede due turni e provoca surriscaldamento (applicata sempre su Impo)."}
RAFFREDDAMENTO_ = {"ita": u"Raffreddamento:"}
ANN_IL_SUR_MA_RIC_DUE_TUR_APP_SEM_SU_IMP = {"ita": u"Annulla il surriscaldamento ma richiede due turni (applicata sempre su Impo)."}
EFFICIENZA_ = {"ita": u"Efficienza:"}
TUT_LE_TEC_COS_LA_MET_DEI_PE_APP_SEM_SU_IMP_SI_ANN_CON_SUR = {"ita": u"Tutte le Azio-Impofoglie consumano la metà dei <*>#italic#PE<*> (applicata sempre su Impo). Si annulla con surriscaldamento."}
SCOSSA_ = {"ita": u"Scossa:"}
INF_DAN_A_UN_NEM_VIC = {"ita": u"Infligge danni a un nemico vicino."}
SCOSSA_P_ = {"ita": u"Scossa +:"}
INF_MOL_DAN_A_UN_NEM_VIC = {"ita": u"Infligge molti danni a un nemico vicino."}
SCOSSA_PP_ = {"ita": u"Scossa ++:"}
INF_ENO_DAN_A_UN_NEM_VIC = {"ita": u"Infligge enormi danni a un nemico vicino."}
FRECCIA_ELETTRICA_ = {"ita": u"Freccia elettrica:"}
INF_DAN_A_DIS_A_UN_NEM = {"ita": u"Infligge danni a distanza a un nemico."}
FRE_ELE_P_ = {"ita": u"Freccia elettrica +:"}
INF_MOL_DAN_A_DIS_A_UN_NEM = {"ita": u"Infligge molti danni a distanza a un nemico."}
FRE_ELE_PP_ = {"ita": u"Freccia Elettrica ++:"}
INF_ENO_DAN_A_DIS_A_UN_NEM = {"ita": u"Infligge enormi danni a distanza a un nemico."}
TEMPESTA_ELETTRICA_ = {"ita": u"Tempesta elettrica:"}
INF_DAN_A_TUT_I_NEM_O_ALL_NEL_RAG_VIS_DI_IMP = {"ita": u"Infligge danni a tutti i nemici o alleati nel raggio visivo di Impo."}
TEM_ELE_P_ = {"ita": u"Tempesta elettrica +:"}
INF_MOL_DAN_A_TUT_I_NEM_O_ALL_NEL_RAG_VIS_DI_IMP = {"ita": u"Infligge molti danni a tutti i nemici o alleati nel raggio visivo di Impo."}
TEM_ELE_PP_ = {"ita": u"Tempesta elettrica ++:"}
INF_ENO_DAN_A_TUT_I_NEM_O_ALL_NEL_RAG_VIS_DI_IMP = {"ita": u"Infligge enormi danni a tutti i nemici o alleati nel raggio visivo di Impo."}
VELOCIZZA_ = {"ita": u"Velocizza:"}
PER_A_IMP_DI_ESE_DUE_AZI_AL_TUR_APP_SEM_SU_IMP_SI_ANN_CON_SUR = {"ita": u"Permette a Impo di eseguire due azioni al turno (applicata sempre su Impo). Si annulla con surriscaldamento."}
SACCHE_ENERGETICHE = {"ita": u"Sacche Energetiche"}
PRIORIT = {"ita": u"Priorità"}
CONDIZIOIMPOFOGLIO = {"ita": u"Condizio-Impofoglia"}
AZIOIMPOFOGLIO = {"ita": u"Azio-Impofoglia"}
PUN_ENE_ = {"ita": u"Punti energia: "}
SACCA_PICCOLA = {"ita": u"Sacca piccola:"}
SAC_ENE_CHE_PU_CON_POC_ALI = {"ita": u"Sacca Energetica che può contenere poca alimentazione."}
SACCA_DISCRETA = {"ita": u"Sacca discreta:"}
SAC_ENE_CON_UNA_BUO_CAP_E_OTT_DEL_SIS_DIF = {"ita": u"Sacca Energetica con una buona capienza e ottimizzazione del sistema difensivo."}
SACCA_CAPIENTE = {"ita": u"Sacca capiente:"}
SAC_ENE_CON_UNA_GRA_CAP_E_UN_OTT_SIS_DIF = {"ita": u"Sacca Energetica con una grande capacità e un ottimo sistema difensivo."}
SACCA_GRANDE = {"ita": u"Sacca grande:"}
GRA_SAC_ENE_CHE_PER_A_IMP_DI_UTI_LE_TEC_PI_DIS = {"ita": u"Grande Sacca Energetica che permette a Impo di utilizzare le Azio-Impofoglie più dispendiose."}
SACCA_ENORME = {"ita": u"Sacca enorme:"}
SAC_ENE_INC_CAP_PER_UN_ECC_OTT_DEL_SIS_DIF = {"ita": u"Sacca Energetica incredibilmente capiente. Permette un eccellente ottimizzazione del sistema difensivo."}
PRIORIT_ = {"ita": u"Priorità:"}
IND_LA_PRI_DEL_IMP_ESE_LAZ_ASS_ALL_PRI_CON_VER_DEL_LIS = {"ita": u"Indica la priorità dell'azione. Impo eseguirà l'azione associata alla prima condizione verificata della lista."}
CONDIZIOIMPOFOGLIO_ = {"ita": u"Condizio-Impofoglia:"}
IND_LA_SIT_CHE_SI_DEV_VER_AFF_IMP_ESE_LAZ_ASS = {"ita": u"Indica la situazione che si deve verificare affinché Impo esegua l'Azio-Impofoglia associata."}
AZIOIMPOFOGLIO_ = {"ita": u"Azio-Impofoglia:"}
IND_LAZ_CHE_IMP_ESE_QUA_SI_VER_LA_CON_NEL_CON_ASS = {"ita": u"Indica l'azione che Impo eseguirà quando si verifica la condizione nella Condizio-Impofoglia associata."}
SLO_DI_MEM_VUO = {"ita": u"Slot di memoria vuoto..."}
SLO_DI_MEM_DAN = {"ita": u"Slot di memoria danneggiato..."}
SALVANDO = {"ita": u"Salvando..."}
CANCELLANDO = {"ita": u"Cancellando..."}
CARICA_PARTITA = {"ita": u"Carica partita"}
CANCELLA_PARTITA = {"ita": u"Cancella partita"}
SALVA_PARTITA = {"ita": u"Salva partita"}
SLOT_VUOTO = {"ita": u"Slot vuoto"}
LIVELLO_ = {"ita": u"Livello: "}
SLOT_CORROTTO = {"ita": u"Slot corrotto"}
TAS_CEN_CAN_PAR = {"ita": u"Tasto centrale: cancella partita"}
Y_CAN_PAR = {"ita": u"Y: cancella partita"}
SHI_CAN_PAR = {"ita": u"SHIFT: cancella partita"}
TAS_CEN_SAL_PAR = {"ita": u"Tasto centrale: salva partita"}
Y_SAL_PAR = {"ita": u"Y: salva partita"}
SHI_SAL_PAR = {"ita": u"SHIFT: salva partita"}
TAS_CEN_CAR_PAR = {"ita": u"Tasto centrale: carica partita"}
Y_CAR_PAR = {"ita": u"Y: carica partita"}
SHI_CAR_PAR = {"ita": u"SHIFT: carica partita"}
CONFERMI = {"ita": u"Confermi?"}
SALVATO = {"ita": u"Salvato!"}
CANCELLATO = {"ita": u"Cancellato!"}
_SU = {"ita": u": Su"}
_GIU = {"ita": u": Giù"}
_SINISTRA = {"ita": u": Sinistra"}
_DESTRA = {"ita": u": Destra"}
_INDIETRO = {"ita": u": Indietro"}
_MOD_INTERAZIONE = {"ita": u": Mod. interazione"}
RAF_IN_COR = {"ita": u"Raffreddamento in corso"}
SAC_ENE_IN_CAR = {"ita": u"Sacca Energetica in carica"}
TEM_TRO_ELE = {"ita": u"Temperatura troppo elevata"}
ENERGIA_INSUFFICIENTE = {"ita": u"Energia insufficiente"}
IMPOPIETRA_SPENTA = {"ita": u"Impopietra spenta"}
CEL_DI_MEM_INC = {"ita": u"Cella di memoria incompleta"}
CON_NON_RIS = {"ita": u"Condizione non rispettata"}
POS_OBI_SCO = {"ita": u"Posizione obiettivo sconosciuta"}
OBIETTIVO_IRRAGGIUNGIBILE = {"ita": u"Obiettivo irraggiungibile"}
AZI_IMP_CON_SUR = {"ita": u"Azione impraticabile con surriscaldamento"}
NES_OBI_IN_MEM = {"ita": u"Nessun obiettivo in memoria"}
COMPRA_ = {"ita": u"Compra!"}
CARICAMENTO___ = {"ita": u"Caricamento..."}
STR_PER_CIT = {"ita": u"Strada per Città"}
CAS_DI_DAV = {"ita": u"Casa di David"}
BIBLIOTECA = {"ita": u"Biblioteca"}
STR_PER_SEL_ARI = {"ita": u"Strada per Selva Arida"}
CAS_DI_NEI___EST = {"ita": u"Castello di Neil - Esterno"}
CAS_DI_NEI___INT = {"ita": u"Castello di Neil - Interno"}
SCO_SUL_MON = {"ita": u"Scorciatoia sulle montagne"}
STR_PER_PAS_MON = {"ita": u"Strada per Passo Montano"}
GIORNO_1 = {"ita": u"Giorno 1"}
GIORNO_2 = {"ita": u"Giorno 2"}
GIORNO_22 = {"ita": u"Giorno 22"}
_ANNO_13 = {"ita": u" - Anno 13"}
GRAZIE = {"ita": u"Grazie"}
SCR_E_SVI_DA_ = {"ita": u"Scritto e Sviluppato da:"}
TRA_IN_ING_ = {"ita": u"Traduzione Inglese:"}
MUSICA_ = {"ita": u"Musica:"}
SVILUPPATO_CON_ = {"ita": u"Sviluppato con:"}
EFF_AUD_DA_FRE_ = {"ita": u"Effetti Audio da Freesound:"}
RINGRAZIAMENTI_SPECIALI_ = {"ita": u"Ringraziamenti Speciali:"}
MIA_FAM_COM_PYG_COM_FRE = {"ita": u"Famiglia <br> Pygame community <br> Freesound community"}
PYT_2_PYG__PYC_COM_EDI_IDE__LMMS_MUS__GIM_2_IMM_ANI__AUD_EDI_AUD = {"ita": u"Python & Pygame <br> PyCharm Community Edition (IDE) <br> LMMS (Musica) <br> GIMP 2 (Immagini & Animazioni) <br> Audacity (Editing Audio)"}
EQUIPAGGIAMENTO_SOLDATO = {"ita": u"Equipaggiamento soldato"}
BICCHIERE = {"ita": u"Bicchiere"}
MAP_E_DIA = {"ita": u"Mappa e Diario"}
CHIAVE_STANZA = {"ita": u"Chiave stanza"}
LEGNA = {"ita": u"Legna"}
CHIAVE_SEMINTERRATO = {"ita": u"Chiave seminterrato"}
COFANETTO = {"ita": u"Cofanetto"}
ASSISTENTE_BIBLIOTECARIO = {"ita": u"Assistente bibliotecario"}
LIBRO = {"ita": u"Libro"}
LIBRO_SCOPO_DEGLI_IMPO = {"ita": u"Libro (Scopo degli impo)"}
LIBRO_SACCHE_ENERGETICHE = {"ita": u"Libro (Sacche Energetiche)"}
LIBRO_GESTIONE_DELL_IMPOFORZA = {"ita": u"Libro (Gestione dell'impo-forza)"}
LIBRO_IMPOMALUS = {"ita": u"Libro (Impo-malus)"}
LIBRO_MOT_RET_UNI_ACC = {"ita": u"Libro (Moto rettilineo uniformemente accelerato)"}
SERVO = {"ita": u"Servo"}
SOLDATO = {"ita": u"Soldato"}
SPECCHIO = {"ita": u"Specchio"}
CUMULO_IMPO = {"ita": u"Cumulo Impo"}
CADAVERE = {"ita": u"Cadavere"}
SOL_CON_LAN = {"ita": u"Soldato con lancia"}
SOL_CON_ARC = {"ita": u"Soldato con arco"}
SOL_CON_SPA = {"ita": u"Soldato con spada"}
QUADRO = {"ita": u"Quadro"}
CADAVERE_SOLDATO = {"ita": u"Cadavere soldato"}
LIB_SUL_COS_VOL1_ETI = {"ita": u"Libro (Sulla coscienza Vol.1 - Etica)"}
LIB_SUL_COS_VOL2_LIB_ARB = {"ita": u"Libro (Sulla coscienza Vol.2 - Libero arbitrio)"}
LIB_SUL_COS_VOL3_TEM = {"ita": u"Libro (Sulla coscienza Vol.3 - Tempo)"}
LIB_SUL_COS_VOL4_REA = {"ita": u"Libro (Sulla coscienza Vol.4 - Realtà)"}
LIB_SUL_EVO = {"ita": u"Libro (Sull'evoluzione)"}
LIB_SUL_CON = {"ita": u"Libro (Sul conflitto)"}
APP_DI_NEI = {"ita": u"Appunti di Neil"}
VALVOLA = {"ita": u"Valvola"}
CAPSULA = {"ita": u"Capsula"}
RATTO = {"ita": u"Ratto"}
LET_DI_NEI = {"ita": u"Lettera di Neil"}
IST_PER_IL_CAL_DI_EVE = {"ita": u"Istruzioni per il Calcolatore Di Eventi"}
MACCHINARIO = {"ita": u"Macchinario"}
NESSUNO = {"ita": u"Nessuno"}
VOCE_SCONOSCIUTA = {"ita": u"Voce sconosciuta"}
APP_DI_ROD = {"ita": u"Appunti di Rod"}
MUC_DI_IMP = {"ita": u"Mucchio di Impo"}
TUTORIAL = {"ita": u"Tutorial"}
COMPUTER = {"ita": u"Computer"}
